import { Lesson } from '../types/teaching';

export const CURRICULUM_LESSONS: Lesson[] = [
  // 1. الجمع بالعد (العد التصاعدي على خط الأعداد)
  {
    id: 'add_count_on',
    titleAr: 'الجمع بالعد التصاعدي',
    subtitleAr: 'ابدأ من العدد الأكبر واعد للأمام',
    category: 'addition_strategies',
    worldId: 'addition',
    icon: '📏',
    colorTheme: 'from-amber-500 to-orange-600',
    conceptAr: 'العد التنازلي والتصاعدي على خط الأعداد انطلاقاً من العدد الأكبر لتسهيل الحساب الذهني.',
    objectiveAr: 'أن يجمع التلميذ عددين بالبدء من العدد الأكبر والقفز للأمام بمقدار العدد الأصغر.',
    prerequisitesAr: ['العد حتى 20', 'التعرف على العدد الأكبر'],
    supportedRepresentations: ['number_line', 'objects', 'vertical_equation'],
    storyIntro: {
      characterName: 'ميرو الكشاف',
      scenarioAr: 'يقف ميرو عند الشجرة رقم 7 في وادي الجمع، ويريد جمع 4 حبات ذهبية مخبأة في الحفر التالية!',
      dialogueAr: 'يا بطل! هل نحتاج للعد من الصفر؟ لا، الأسهل أن نقف عند 7 ونقفز 4 خطوات للأمام!',
      sceneEmoji: '🐾 🌳 7 ➡️ ?',
    },
    prediction: {
      questionAr: 'إذا بدأنا القفز من 7 وقفزنا 4 خطوات للأمام، أين سنصل؟',
      options: [
        { id: 'opt1', textAr: 'سنصل للعدد 11 لأن 7 + 4 = 11', isCorrect: true, explanationAr: 'صحيح! 8، 9، 10، 11!' },
        { id: 'opt2', textAr: 'سنصل للعدد 10', isCorrect: false, explanationAr: 'عد 4 خطوات كاملة: 8، 9، 10، 11.' },
        { id: 'opt3', textAr: 'سنصل للعدد 3', isCorrect: false, explanationAr: 'في الجمع نتحرك للأمام وتكبر الأعداد!' },
      ],
    },
    discoveryActivity: {
      id: 'act_discover_count_on',
      promptAr: 'ساعد ميرو في القفز من 7 أربع خطوات للأمام على خط الأعداد.',
      instructionAr: 'اضغط على زر القفز (+1) أربع مرات وشاهد الأرقام تصعد.',
      initialState: { start: 7, steps: 4 },
      targetState: { end: 11 },
      availableRepresentations: ['number_line'],
      defaultRepresentation: 'number_line',
      whyExplanation: {
        questionAr: 'ليه بنبدأ دايماً من العدد الأكبر؟',
        answerAr: 'لأن البدء من 7 والقفز 4 خطوات أسرع وأسهل ذهنياً بكثير من البدء من 4 والقفز 7 خطوات! الجمع تبادلي والنتيجة واحدة، لكن الذكاء في السرعة!',
        visualConcept: '7 ➕ 4 🟰 4 ➕ 7 🟰 11',
      },
      walkthroughSteps: [
        { titleAr: 'حدد العدد الأكبر', textAr: 'بين 7 و 4، العدد 7 هو الأكبر، فنقف عنده.', visualHintAr: '📍 7' },
        { titleAr: 'اقفز 4 خطوات', textAr: 'نعد تصاعدياً: 8، ثم 9، ثم 10، ثم 11!', visualHintAr: '🦘 8 ➡️ 9 ➡️ 10 ➡️ 11' },
        { titleAr: 'الوصول للناتج', textAr: 'إذن 7 + 4 = 11 بكل ثقة!', visualHintAr: '🎯 11' },
      ],
      hintAr: 'ابدأ من 7 واضغط على زر القفز خطوة بخطوة حتى تصل إلى 11.',
    },
    interactiveLab: {
      id: 'act_lab_count_on',
      promptAr: 'حل المسألة 8 + 5 بالقفز على خط الأعداد.',
      instructionAr: 'اقفز 5 قفزات بدءاً من 8.',
      initialState: { start: 8, steps: 5 },
      targetState: { end: 13 },
      availableRepresentations: ['number_line', 'objects'],
      defaultRepresentation: 'number_line',
      whyExplanation: {
        questionAr: 'ما العلاقة بين خط الأعداد وعملية الجمع؟',
        answerAr: 'خط الأعداد يمثل الأعداد مرتبة، والجمع يعني التحرك جهة اليمين (للأمام) بمقدار ما نضيفه!',
        visualConcept: '➡️ زيادة ➡️ جمع ➡️ تحرك للأمام',
      },
      walkthroughSteps: [
        { titleAr: 'قف عند 8', textAr: 'مكان البداية هو 8.', visualHintAr: '8' },
        { titleAr: 'اقفز 5 خطوات', textAr: '8 + 5 = 13.', visualHintAr: '13' },
      ],
      hintAr: 'اضغط زر القفز 5 مرات.',
    },
    practiceChallenges: [],
    realWorldApplication: {
      scenarioAr: 'مع ليلى 9 جنيهات في حصالتها، أعطاها والدها 4 جنيهات مكافأة لتفوقها.',
      character: 'ليلى',
      promptAr: 'كم جنيهاً أصبح مع ليلى؟ (ابدأ من 9 وعد 4 خطوات للأمام)',
      activity: {
        id: 'act_apply_count_on',
        promptAr: '9 + 4 = ؟',
        instructionAr: 'استخدم خط الأعداد للوصول للناتج.',
        initialState: { start: 9, steps: 4 },
        targetState: { end: 13 },
        availableRepresentations: ['number_line'],
        defaultRepresentation: 'number_line',
        whyExplanation: {
          questionAr: 'كيف نستخدم هذا في النقود اليومية؟',
          answerAr: 'نحتفظ بالمبلغ الأكبر في ذهننا، ونعد الجنيهات المضافة واحداً تلو الآخر!',
          visualConcept: '🪙 9 ➕ 4 🟰 13 جنيهاً',
        },
        walkthroughSteps: [],
        hintAr: 'ابدأ من 9 وقفز 4 مرات تصاعدياً.',
      },
    },
    transferTest: {
      promptAr: 'اختبر نفسك بمسألة جديدة: 12 + 3 = ؟',
      representation: 'number_line',
      activity: {
        id: 'transfer_count_on',
        promptAr: '12 + 3 = 15',
        instructionAr: 'اقفز 3 خطوات من 12.',
        initialState: { start: 12, steps: 3 },
        targetState: { end: 15 },
        availableRepresentations: ['number_line'],
        defaultRepresentation: 'number_line',
        whyExplanation: {
          questionAr: 'ليه الناتج 15؟',
          answerAr: '12 تليها 13، 14، 15!',
          visualConcept: '12 ➡️ 13 ➡️ 14 ➡️ 15',
        },
        walkthroughSteps: [],
        hintAr: 'اقفز 3 مرات للأمام.',
      },
    },
    whyExplanation: {
      questionAr: 'لماذا نسمي هذه الاستراتيجية "الجمع بالعد"؟',
      answerAr: 'لأننا لا نبدأ العد من الرقم 1، بل نكمل العد انطلاقاً من العدد الأكبر، وهو ما يوفر الجهد الذهني ويمنع الخطأ!',
      interactiveDemoType: 'number_line',
    },
  },

  // 2. الجمع بالمضاعفة وشبه المضاعفة (Doubles & Near Doubles)
  {
    id: 'add_doubles',
    titleAr: 'الجمع بالمضاعفة وشبه المضاعفة',
    subtitleAr: 'استخدم حقائق المضاعفة لحل 6 + 6 ثم 6 + 7',
    category: 'addition_strategies',
    worldId: 'addition',
    icon: '👯',
    colorTheme: 'from-purple-500 to-indigo-600',
    conceptAr: 'استغلال حفظ حقائق جمع العدد ونفسه (المضاعف) لحل المسائل القريبة منها بإضافة أو طرح 1.',
    objectiveAr: 'أن يدرك التلميذ أن 6 + 6 = 12، وبالتالي 6 + 7 هي (6 + 6 + 1 = 13).',
    prerequisitesAr: ['الأعداد حتى 20'],
    supportedRepresentations: ['ten_frame', 'objects', 'vertical_equation'],
    storyIntro: {
      characterName: 'ميرو والتوأم السحري',
      scenarioAr: 'يرتب ميرو البلورات في صفيحتين متساويتين تماماً: 6 بلورات زرقاء و 6 بلورات خضراء!',
      dialogueAr: 'انظر يا بطل! المجموعتان متطابقتان تماماً كالتوأم! ما هو ضعف العدد 6؟',
      sceneEmoji: '💎💎💎💎💎💎 | 💎💎💎💎💎💎',
    },
    prediction: {
      questionAr: 'إذا عرفنا أن 6 + 6 = 12، تفتكر ناتج 6 + 7 هيكون كام؟',
      options: [
        { id: 'opt1', textAr: '13 (لأن 7 تزيد عن 6 بمقدار 1)', isCorrect: true, explanationAr: 'رائع! 12 + 1 = 13!' },
        { id: 'opt2', textAr: '12 (نفس الناتج)', isCorrect: false, explanationAr: 'لا، لأن أحد العددين زاد 1!' },
        { id: 'opt3', textAr: '14', isCorrect: false, explanationAr: 'زيادة 1 فقط على 12 تعطي 13.' },
      ],
    },
    discoveryActivity: {
      id: 'act_discover_doubles',
      promptAr: 'لاحظ الصفيحتين: 6 في الأولى و 6 في الثانية. كم المجموع؟',
      instructionAr: 'شاهد تماثل المجموعتين في إطار العشرة.',
      initialState: { count1: 6, count2: 6 },
      targetState: { total: 12 },
      availableRepresentations: ['ten_frame'],
      defaultRepresentation: 'ten_frame',
      whyExplanation: {
        questionAr: 'ليه حقائق المضاعفة سحرية وسريعة؟',
        answerAr: 'لأنها أزواج متطابقة يسهل حفظها ذهنياً: 5+5=10، 6+6=12، 7+7=14، ومنها نستنتج المسائل الأصعب!',
        visualConcept: '6 ➕ 6 🟰 12 👈 ومنها 6 ➕ 7 🟰 12 ➕ 1 🟰 13',
      },
      walkthroughSteps: [
        { titleAr: 'مجموعة أولى 6', textAr: 'لدينا 6 عناصر.', visualHintAr: '6' },
        { titleAr: 'مجموعة ثانية 6', textAr: 'ضعف الـ 6 يعني 6 + 6 = 12.', visualHintAr: '12' },
        { titleAr: 'شبه المضاعف (+1)', textAr: 'إذا كانت المسألة 6 + 7، نفكك 7 إلى (6 + 1)، فيكون 12 + 1 = 13!', visualHintAr: '13' },
      ],
      hintAr: 'ضعف الـ 6 هو 12، وبإضافة 1 تصبح 13.',
    },
    interactiveLab: {
      id: 'act_lab_doubles',
      promptAr: 'جرب استراتيجية شبه المضاعفة مع: 7 + 8 = ؟',
      instructionAr: 'استخدم حقيقة 7 + 7 = 14، ثم أضف 1 الزائد من العدد 8.',
      initialState: { count1: 7, count2: 8 },
      targetState: { total: 15 },
      availableRepresentations: ['ten_frame'],
      defaultRepresentation: 'ten_frame',
      whyExplanation: {
        questionAr: 'كيف فكرنا فيها؟',
        answerAr: '7 + 7 = 14، والعدد 8 يزيد عن 7 بواحد، إذن 14 + 1 = 15!',
        visualConcept: '7 ➕ 8 🟰 (7 ➕ 7) ➕ 1 🟰 15',
      },
      walkthroughSteps: [],
      hintAr: '7 + 7 = 14، إذن 7 + 8 = 15.',
    },
    practiceChallenges: [],
    realWorldApplication: {
      scenarioAr: 'في قفص الطيور، وقف 5 عصافير على الغصن الأيمن، و 6 عصافير على الغصن الأيسر.',
      character: 'كريم',
      promptAr: 'استخدم المضاعفة لحساب مجموع العصافير: (5 + 5 + 1)',
      activity: {
        id: 'act_apply_doubles',
        promptAr: '5 + 6 = ؟',
        instructionAr: '5 + 5 = 10، إذن 5 + 6 = 11.',
        initialState: { count1: 5, count2: 6 },
        targetState: { total: 11 },
        availableRepresentations: ['ten_frame'],
        defaultRepresentation: 'ten_frame',
        whyExplanation: {
          questionAr: 'لماذا 11؟',
          answerAr: 'لأن ضعف 5 هو 10، و 6 تزيد بمقدار 1، إذن 11!',
          visualConcept: '5 ➕ 6 🟰 10 ➕ 1 🟰 11',
        },
        walkthroughSteps: [],
        hintAr: 'ضعف 5 هو 10، أضف 1 ليصبح 11.',
      },
    },
    transferTest: {
      promptAr: 'ما هو ناتج 8 + 9 باستخدام حقيقة 8 + 8 = 16؟',
      representation: 'ten_frame',
      activity: {
        id: 'transfer_doubles',
        promptAr: '8 + 9 = 17',
        instructionAr: '16 + 1 = 17.',
        initialState: { count1: 8, count2: 9 },
        targetState: { total: 17 },
        availableRepresentations: ['ten_frame'],
        defaultRepresentation: 'ten_frame',
        whyExplanation: {
          questionAr: 'كيف استنتجتها؟',
          answerAr: '8 + 8 = 16، وبإضافة 1 تصبح 17!',
          visualConcept: '8 ➕ 9 🟰 17',
        },
        walkthroughSteps: [],
        hintAr: '16 + 1 = 17.',
      },
    },
    whyExplanation: {
      questionAr: 'لماذا نعلم الأطفال شبه المضاعفة؟',
      answerAr: 'لأنها تحول مسألة جمع جديدة إلى حقيقة مألوفة وسريعة جداً بدون الحاجة للعد بالأصابع!',
      interactiveDemoType: 'ten_frame',
    },
  },

  // 3. الجمع بإضافة 10 (24 + 10 = 34)
  {
    id: 'add_plus_ten',
    titleAr: 'الجمع بإضافة 10',
    subtitleAr: 'لاحظ كيف تتغير خانة العشرات فقط',
    category: 'addition_strategies',
    worldId: 'addition',
    icon: '🔟',
    colorTheme: 'from-sky-500 to-blue-700',
    conceptAr: 'عند إضافة 10 إلى أي عدد، تزيد خانة العشرات بمقدار 1 فقط، وتبقى خانة الآحاد كما هي دون أي تغيير.',
    objectiveAr: 'أن يجمع التلميذ 10 ذهنياً إلى أي عدد مكون من رقمين بملاحظة ثبات الآحاد وزيادة العشرات.',
    prerequisitesAr: ['القيمة المكانية للآحاد والعشرات'],
    supportedRepresentations: ['place_value', 'chart_120', 'vertical_equation'],
    storyIntro: {
      characterName: 'ميرو وحزمة القصب',
      scenarioAr: 'جمع ميرو 24 حزمة قصب (عمودان من عشرة و 4 حبات مفردة). وجد حزمة عشرة كاملة إضافية!',
      dialogueAr: 'يا بطل! أضفنا عمود عشرة جديد! انظر جيداً: هل تغيرت الحبات المفردة (الآحاد)؟ أم العشرات فقط؟',
      sceneEmoji: '🎋 24 ➕ 10 🟰 ?',
    },
    prediction: {
      questionAr: 'عند إضافة 10 للعدد 24، ماذا سيحدث لخانة الآحاد (4)؟',
      options: [
        { id: 'opt1', textAr: 'ستبقى 4 كما هي، وتصبح العشرات 3 (الناتج 34)', isCorrect: true, explanationAr: 'عبقري! لأننا أضفنا 0 في الآحاد و 1 في العشرات!' },
        { id: 'opt2', textAr: 'ستتغير الآحاد وتصبح 5', isCorrect: false, explanationAr: 'الآحاد لا تتغير لأننا نضيف عشرة كاملة.' },
        { id: 'opt3', textAr: 'سيصبح الناتج 25', isCorrect: false, explanationAr: '25 إذا أضفنا 1، لكننا أضفنا 10!' },
      ],
    },
    discoveryActivity: {
      id: 'act_discover_plus_ten',
      promptAr: 'لدينا 24 (2 عشرات و 4 آحاد). أضف عمود عشرة واحد وشاهد المجموع.',
      instructionAr: 'لاحظ زيادة العشرات من 2 إلى 3 وبقاء الآحاد 4.',
      initialState: { tens: 2, ones: 4 },
      targetState: { tens: 3, ones: 4, total: 34 },
      availableRepresentations: ['place_value', 'chart_120'],
      defaultRepresentation: 'place_value',
      whyExplanation: {
        questionAr: 'ليه الآحاد ما اتغيرتش لما ضفنا 10؟',
        answerAr: 'لأن العدد 10 يتكون من: 1 في العشرات و 0 في الآحاد! إضافة صفر لأي رقم لا يغير قيمته: 4 + 0 = 4!',
        visualConcept: '24 ➕ 10 🟰 (20 ➕ 10) ➕ (4 ➕ 0) 🟰 30 ➕ 4 🟰 34',
      },
      walkthroughSteps: [
        { titleAr: 'مثل العدد 24', textAr: '24 = عمودين عشرات (20) + 4 مكعبات آحاد (4).', visualHintAr: '2T + 4O' },
        { titleAr: 'أضف عمود عشرة (+10)', textAr: 'تصبح العشرات: 2 + 1 = 3 عشرات (30).', visualHintAr: '+1T' },
        { titleAr: 'الآحاد ثابتة', textAr: 'تبقى الآحاد 4، فيكون الناتج 34!', visualHintAr: '34' },
      ],
      hintAr: '2 عشرات + 1 عشرة = 3 عشرات، والآحاد 4 كما هي -> 34.',
    },
    interactiveLab: {
      id: 'act_lab_plus_ten',
      promptAr: 'احسب ذهنياً: 53 + 10 = ؟',
      instructionAr: 'زد العشرات 1 واترك الآحاد كما هي.',
      initialState: { tens: 5, ones: 3 },
      targetState: { tens: 6, ones: 3, total: 63 },
      availableRepresentations: ['place_value', 'chart_120'],
      defaultRepresentation: 'place_value',
      whyExplanation: {
        questionAr: 'كيف نتحقق على لوحة الـ 120؟',
        answerAr: 'على لوحة الـ 120، إضافة 10 تعني النزول صفاً واحداً لأسفل مباشرة تحت العدد!',
        visualConcept: '⬇️ خطوة للأسفل = +10',
      },
      walkthroughSteps: [],
      hintAr: '5 عشرات تصبح 6 عشرات، والآحاد 3 -> 63.',
    },
    practiceChallenges: [],
    realWorldApplication: {
      scenarioAr: 'في متجر الألعاب، كان مع فريدة 47 بطاقة سحرية، واشترت حزمة من 10 بطاقات جديدة.',
      character: 'فريدة',
      promptAr: 'كم بطاقة مع فريدة الآن؟ 47 + 10 = ؟',
      activity: {
        id: 'act_apply_plus_ten',
        promptAr: '47 + 10 = 57',
        instructionAr: 'زد العشرات 1.',
        initialState: { tens: 4, ones: 7 },
        targetState: { tens: 5, ones: 7, total: 57 },
        availableRepresentations: ['place_value'],
        defaultRepresentation: 'place_value',
        whyExplanation: {
          questionAr: 'لماذا 57؟',
          answerAr: '40 + 10 = 50، مع 7 آحاد = 57 بطاقة!',
          visualConcept: '47 ➕ 10 🟰 57',
        },
        walkthroughSteps: [],
        hintAr: '4 عشرات + 1 عشرة = 5 عشرات، والآحاد 7 -> 57.',
      },
    },
    transferTest: {
      promptAr: 'ما ناتج 62 + 10؟',
      representation: 'place_value',
      activity: {
        id: 'transfer_plus_ten',
        promptAr: '62 + 10 = 72',
        instructionAr: 'زد العشرات 1 تصبح 7، والآحاد 2.',
        initialState: { tens: 6, ones: 2 },
        targetState: { tens: 7, ones: 2, total: 72 },
        availableRepresentations: ['place_value'],
        defaultRepresentation: 'place_value',
        whyExplanation: {
          questionAr: 'كيف نزيد العشرات؟',
          answerAr: '6 + 1 = 7 عشرات والآحاد 2 -> 72.',
          visualConcept: '62 ➕ 10 🟰 72',
        },
        walkthroughSteps: [],
        hintAr: 'العشرات تزيد 1 -> 72.',
      },
    },
    whyExplanation: {
      questionAr: 'ما فائدة تعلم الجمع بإضافة 10؟',
      answerAr: 'هو أساس الحساب الذهني ولوحة الـ 120، ويجعل الطفل يفهم النظام العشري والقيمة المكانية بعمق!',
      interactiveDemoType: 'chart_120',
    },
  },

  // 4. الجمع بتكوين العشرة (Make Ten: 8 + 5 = 10 + 3 = 13)
  {
    id: 'add_make_ten',
    titleAr: 'الجمع بتكوين العشرة',
    subtitleAr: 'اصنع 10 أولاً لتجعل الجمع سهلاً',
    category: 'addition_strategies',
    worldId: 'addition',
    icon: '🎯',
    colorTheme: 'from-amber-600 to-rose-600',
    conceptAr: 'تفكيك العدد الأصغر لإكمال العدد الأكبر إلى عشرة كاملة (10)، ثم جمع الباقي مع الـ 10.',
    objectiveAr: 'أن يحل التلميذ مسألة مثل 8 + 5 بأخذ 2 من الـ 5 لتكوين 10، فيصبح 10 + 3 = 13.',
    prerequisitesAr: ['مكونات العدد 10', 'الجمع حتى 20'],
    supportedRepresentations: ['ten_frame', 'objects', 'number_line', 'vertical_equation'],
    storyIntro: {
      characterName: 'ميرو وحبوب البلور',
      scenarioAr: 'سلة ميرو الأولى بها 8 حبات برتقالية، وتحتاج حبتين فقط لتكتمل وتصبح 10 كاملة! وفي السلة الثانية 5 حبات خضراء.',
      dialogueAr: 'يا ذكي! ما رأيك أن ننقل حبتين من السلة الثانية إلى الأولى لنصنع 10؟ ما أسهل الجمع مع العشرة!',
      sceneEmoji: '🧺 8 ➕ 5 🟰 (8 ➕ 2) ➕ 3 🟰 ?',
    },
    prediction: {
      questionAr: 'العدد 8 يحتاج كام عشان يبقى 10 كاملة؟',
      options: [
        { id: 'opt1', textAr: 'يحتاج 2 (لأن 8 + 2 = 10)', isCorrect: true, explanationAr: 'ممتاز! 8 ينقصها 2 فقط لتصبح 10 كاملة!' },
        { id: 'opt2', textAr: 'يحتاج 3', isCorrect: false, explanationAr: '8 + 2 = 10.' },
        { id: 'opt3', textAr: 'يحتاج 5', isCorrect: false, explanationAr: '8 + 5 = 13 وليس 10.' },
      ],
    },
    discoveryActivity: {
      id: 'act_discover_make_ten',
      promptAr: 'انقل حبتين من إطار الخمسة إلى إطار الثمانية لتكوين عشرة كاملة.',
      instructionAr: 'اضغط على زر نقل تفاحة لتملأ إطار العشرة الأول.',
      initialState: { count1: 8, count2: 5 },
      targetState: { count1: 10, count2: 3, total: 13 },
      availableRepresentations: ['ten_frame'],
      defaultRepresentation: 'ten_frame',
      whyExplanation: {
        questionAr: 'ليه تكوين العشرة أسهل وأذكى طريقة في الجمع؟',
        answerAr: 'لأن عقولنا تحب العدد 10! جمع أي رقم مع 10 فوري وسهل جداً: 10 + 3 = 13 مباشرة بدون عد على الأصابع!',
        visualConcept: '8 ➕ 5 🟰 (8 ➕ 2) ➕ 3 🟰 10 ➕ 3 🟰 13',
      },
      walkthroughSteps: [
        { titleAr: 'نحدد ما ينقص لتكوين 10', textAr: 'العدد 8 يحتاج 2 ليصبح 10.', visualHintAr: '8 + 2 = 10' },
        { titleAr: 'نأخذ 2 من العدد 5', textAr: 'نفكك 5 إلى (2 + 3).', visualHintAr: '5 = 2 + 3' },
        { titleAr: 'نجمع مع العشرة', textAr: '10 + 3 = 13!', visualHintAr: '10 + 3 = 13' },
      ],
      hintAr: 'انقل عنصرين لتملأ الإطار الأول فيصبح 10، ويتبقى في الإطار الثاني 3.',
    },
    interactiveLab: {
      id: 'act_lab_make_ten',
      promptAr: 'حل المسألة 7 + 5 بتكوين العشرة.',
      instructionAr: 'العدد 7 يحتاج 3 من الـ 5 ليصبح 10، فكم يتبقى من الـ 5؟ 10 + 2 = 12.',
      initialState: { count1: 7, count2: 5 },
      targetState: { count1: 10, count2: 2, total: 12 },
      availableRepresentations: ['ten_frame'],
      defaultRepresentation: 'ten_frame',
      whyExplanation: {
        questionAr: 'كيف فككنا العدد 5؟',
        answerAr: 'الـ 7 تحتاج 3، فأخذنا 3 من الـ 5 فتبقى 2! إذن 10 + 2 = 12!',
        visualConcept: '7 ➕ 5 🟰 (7 ➕ 3) ➕ 2 🟰 10 ➕ 2 🟰 12',
      },
      walkthroughSteps: [],
      hintAr: 'انقل 3 لتصنع 10، ثم 10 + 2 = 12.',
    },
    practiceChallenges: [],
    realWorldApplication: {
      scenarioAr: 'في حفل المدرسة، وضع حازم 9 بالونات حمراء في قوس المدخل، ثم أضاف 6 بالونات زرقاء.',
      character: 'حازم',
      promptAr: 'كم بالوناً في القوس؟ (9 تحتاج 1 فقط لتصبح 10!)',
      activity: {
        id: 'act_apply_make_ten',
        promptAr: '9 + 6 = (9 + 1) + 5 = 10 + 5 = 15',
        instructionAr: 'انقل 1 بالون ليصبح 10 + 5 = 15.',
        initialState: { count1: 9, count2: 6 },
        targetState: { count1: 10, count2: 5, total: 15 },
        availableRepresentations: ['ten_frame'],
        defaultRepresentation: 'ten_frame',
        whyExplanation: {
          questionAr: 'لماذا كان الحل سريعاً مع الـ 9؟',
          answerAr: 'لأن 9 هي أقرب عدد للعشرة، تحتاج 1 فقط! 9 + 6 = 10 + 5 = 15 فوراً!',
          visualConcept: '9 ➕ 6 🟰 10 ➕ 5 🟰 15',
        },
        walkthroughSteps: [],
        hintAr: 'خذ 1 من الـ 6 لتصنع 10، يتبقى 5 -> 15.',
      },
    },
    transferTest: {
      promptAr: 'احسب ذهنياً: 8 + 6 بتكوين العشرة.',
      representation: 'ten_frame',
      activity: {
        id: 'transfer_make_ten',
        promptAr: '8 + 6 = 10 + 4 = 14',
        instructionAr: '8 تحتاج 2 من 6 لتصبح 10، ويتبقى 4.',
        initialState: { count1: 8, count2: 6 },
        targetState: { count1: 10, count2: 4, total: 14 },
        availableRepresentations: ['ten_frame'],
        defaultRepresentation: 'ten_frame',
        whyExplanation: {
          questionAr: 'كيف وصلنا لـ 14؟',
          answerAr: '8 + 2 = 10، و 6 أخذنا منها 2 فتبقى 4 -> 10 + 4 = 14!',
          visualConcept: '8 ➕ 6 🟰 14',
        },
        walkthroughSteps: [],
        hintAr: '10 + 4 = 14.',
      },
    },
    whyExplanation: {
      questionAr: 'لماذا تركز المناهج الحديثة على استراتيجية تكوين العشرة؟',
      answerAr: 'لأنها الأساس الرياضي المتين لعملية الجمع وإعادة التسمية في الصفوف التالية، وتطور التفكير الجبري لدى الطفل مبكراً!',
      interactiveDemoType: 'ten_frame',
    },
  },

  // 5. الطرح بالعد التنازلي (15 - 4 on Number Line)
  {
    id: 'sub_count_back',
    titleAr: 'الطرح بالعد التنازلي',
    subtitleAr: 'ابدأ من المطروح منه وارجع للخلف',
    category: 'subtraction_strategies',
    worldId: 'subtraction',
    icon: '🔙',
    colorTheme: 'from-rose-500 to-red-700',
    conceptAr: 'الطرح هو حركة للخلف (تنازلياً) على خط الأعداد انطلاقاً من العدد الأكبر المطروح منه.',
    objectiveAr: 'أن يطرح التلميذ بالبدء من العدد الأكبر والرجوع للخلف بمقدار المطروح: 15 - 4 = 11.',
    prerequisitesAr: ['العد التنازلي حتى 20'],
    supportedRepresentations: ['number_line', 'objects', 'vertical_equation'],
    storyIntro: {
      characterName: 'ميرو في كهف الطرح',
      scenarioAr: 'كان ميرو عند البوابة رقم 15 في كهف الطرح، وطلب منه الحارس الرجوع 4 خطوات للخلف لفتح الباب السري!',
      dialogueAr: 'في الطرح نتراجع للخلف وتصغر الأعداد! قف عند 15 وارجع خطوة خطوة: 14، 13، 12، 11!',
      sceneEmoji: '🚪 15 ⬅️ 4 خطوات 🟰 ?',
    },
    prediction: {
      questionAr: 'إذا بدأنا من 15 ورجعنا 4 خطوات للخلف، أين سنصل؟',
      options: [
        { id: 'opt1', textAr: 'سنصل للعدد 11 (14، 13، 12، 11)', isCorrect: true, explanationAr: 'صحيح! 15 - 4 = 11!' },
        { id: 'opt2', textAr: 'سنصل للعدد 19', isCorrect: false, explanationAr: '19 إذا جمعنا، لكن الطرح حركة للخلف!' },
        { id: 'opt3', textAr: 'سنصل للعدد 10', isCorrect: false, explanationAr: 'تراجع 4 خطوات فقط: 15 - 4 = 11.' },
      ],
    },
    discoveryActivity: {
      id: 'act_discover_count_back',
      promptAr: 'ارجع 4 خطوات للخلف على خط الأعداد بدءاً من 15.',
      instructionAr: 'اضغط على زر (ارجع خطوة للخلف −1) أربع مرات.',
      initialState: { start: 15, steps: 4 },
      targetState: { end: 11 },
      availableRepresentations: ['number_line'],
      defaultRepresentation: 'number_line',
      whyExplanation: {
        questionAr: 'ليه بنرجع للخلف على خط الأعداد في الطرح؟',
        answerAr: 'لأن الطرح يعني الأخذ والنقصان، وعلى خط الأعداد الأرقام تصغر كلما تحركنا جهة اليسار (للخلف)!',
        visualConcept: '⬅️ نقصان ⬅️ طرح ⬅️ تراجع للخلف',
      },
      walkthroughSteps: [
        { titleAr: 'قف عند 15', textAr: 'المطروح منه هو 15.', visualHintAr: '15' },
        { titleAr: 'تراجع 4 قفزات', textAr: '14، ثم 13، ثم 12، ثم 11!', visualHintAr: '14 ⬅️ 13 ⬅️ 12 ⬅️ 11' },
        { titleAr: 'الوصول للحل', textAr: 'إذن 15 − 4 = 11!', visualHintAr: '11' },
      ],
      hintAr: 'ابدأ من 15 وارجع 4 خطوات للخلف.',
    },
    interactiveLab: {
      id: 'act_lab_count_back',
      promptAr: 'حل المسألة 14 - 3 بالعد التنازلي.',
      instructionAr: 'ارجع 3 خطوات من 14.',
      initialState: { start: 14, steps: 3 },
      targetState: { end: 11 },
      availableRepresentations: ['number_line'],
      defaultRepresentation: 'number_line',
      whyExplanation: {
        questionAr: 'كيف نعد تنازلياً؟',
        answerAr: 'قبل 14 يأتي: 13، 12، 11! الناتج 11!',
        visualConcept: '14 ➖ 3 🟰 11',
      },
      walkthroughSteps: [],
      hintAr: 'ارجع 3 خطوات: 13، 12، 11.',
    },
    practiceChallenges: [],
    realWorldApplication: {
      scenarioAr: 'كان على الشجرة 16 عصفوراً، طار منها 5 عصافير تبحث عن طعام.',
      character: 'يوسف',
      promptAr: 'كم عصفوراً بقي على الشجرة؟ 16 - 5 = ؟',
      activity: {
        id: 'act_apply_count_back',
        promptAr: '16 - 5 = 11',
        instructionAr: 'ارجع 5 خطوات من 16.',
        initialState: { start: 16, steps: 5 },
        targetState: { end: 11 },
        availableRepresentations: ['number_line'],
        defaultRepresentation: 'number_line',
        whyExplanation: {
          questionAr: 'لماذا 11؟',
          answerAr: '16 - 5 = 11 عصفوراً بقوا على الأغصان.',
          visualConcept: '16 ➖ 5 🟰 11',
        },
        walkthroughSteps: [],
        hintAr: 'ارجع 5 خطوات من 16.',
      },
    },
    transferTest: {
      promptAr: 'اطرح بالعد التنازلي: 18 - 4 = ؟',
      representation: 'number_line',
      activity: {
        id: 'transfer_count_back',
        promptAr: '18 - 4 = 14',
        instructionAr: '17، 16، 15، 14.',
        initialState: { start: 18, steps: 4 },
        targetState: { end: 14 },
        availableRepresentations: ['number_line'],
        defaultRepresentation: 'number_line',
        whyExplanation: {
          questionAr: 'الناتج 14؟',
          answerAr: 'نعم لأن 18 - 4 = 14!',
          visualConcept: '18 ➖ 4 🟰 14',
        },
        walkthroughSteps: [],
        hintAr: 'ارجع 4 خطوات للخلف.',
      },
    },
    whyExplanation: {
      questionAr: 'متى نستخدم الطرح بالعد التنازلي؟',
      answerAr: 'نستخدمه عندما يكون العدد المطروح صغيراً (1 أو 2 أو 3 أو 4 أو 5)، لأن القفزات القليلة سريعة ومضمونة!',
      interactiveDemoType: 'number_line',
    },
  },

  // 6. الطرح بتكوين العشرة (Make Ten Subtraction: 13 - 5 -> 13 - 3 = 10, 10 - 2 = 8)
  {
    id: 'sub_make_ten',
    titleAr: 'الطرح بتكوين العشرة (الرجوع للـ 10)',
    subtitleAr: 'ارجع إلى 10 أولاً ثم اطرح الباقي',
    category: 'subtraction_strategies',
    worldId: 'subtraction',
    icon: '🏰',
    colorTheme: 'from-amber-600 to-red-600',
    conceptAr: 'طرح الآحاد الزائدة للوصول إلى محطة العشرة (10)، ثم طرح المتبقي من الـ 10 بسهولة.',
    objectiveAr: 'أن يحل التلميذ 13 - 5 بطرح 3 أولاً ليصل إلى 10، ثم يطرح 2 الباقية من 10 فيحصل على 8.',
    prerequisitesAr: ['مكونات الـ 10', 'الطرح حتى 20'],
    supportedRepresentations: ['ten_frame', 'objects', 'number_line'],
    storyIntro: {
      characterName: 'ميرو ومحطة الاستراحة',
      scenarioAr: 'مع ميرو 13 تفاحة. يريد أن يأكل 5 تفاحات. قال له الحكيم: ارجع لمحطة الـ 10 أولاً!',
      dialogueAr: 'معنا 13. كم نطرح لنصل إلى 10 بالضبط؟ 3 تفاحات! ثم يتبقى من الـ 5 تفاحتان نطرحهما من 10 فنصل إلى 8!',
      sceneEmoji: '🍎 13 ➡️ (اطرح 3) ➡️ 10 ➡️ (اطرح 2) ➡️ 8',
    },
    prediction: {
      questionAr: 'كم نحتاج أن نطرح من 13 لنصل إلى العدد 10؟',
      options: [
        { id: 'opt1', textAr: 'نطرح 3 (لأن 13 بها 3 آحاد زائدة عن العشرة)', isCorrect: true, explanationAr: 'صحيح! 13 - 3 = 10!' },
        { id: 'opt2', textAr: 'نطرح 5', isCorrect: false, explanationAr: '13 - 5 = 8 وليس 10.' },
        { id: 'opt3', textAr: 'نطرح 1', isCorrect: false, explanationAr: '13 - 1 = 12.' },
      ],
    },
    discoveryActivity: {
      id: 'act_discover_sub_make_ten',
      promptAr: 'حل 13 − 5: أولاً اطرح 3 لتصل إلى 10، ثم اطرح 2 المتبقية.',
      instructionAr: 'شاهد تفكيك العدد 5 إلى (3 + 2).',
      initialState: { count1: 10, count2: 3 },
      targetState: { count1: 8, count2: 0, total: 8 },
      availableRepresentations: ['ten_frame'],
      defaultRepresentation: 'ten_frame',
      whyExplanation: {
        questionAr: 'ليه محطة العشرة مفيدة في الطرح؟',
        answerAr: 'لأن الطرح من 10 سهل جداً بفضل حفظ مكونات العشرة: 10 - 2 = 8 فوراً وبلا تردد!',
        visualConcept: '13 ➖ 5 🟰 (13 ➖ 3) ➖ 2 🟰 10 ➖ 2 🟰 8',
      },
      walkthroughSteps: [
        { titleAr: 'الوصول للعشرة', textAr: '13 − 3 = 10.', visualHintAr: '13 - 3 = 10' },
        { titleAr: 'طرح الباقي', textAr: 'المطروح هو 5، أخذنا منه 3، تبقى 2. نطرحها من 10: 10 − 2 = 8!', visualHintAr: '10 - 2 = 8' },
      ],
      hintAr: '13 - 3 = 10، ثم 10 - 2 = 8.',
    },
    interactiveLab: {
      id: 'act_lab_sub_make_ten',
      promptAr: 'حل المسألة 14 − 6 بتكوين العشرة.',
      instructionAr: '14 − 4 = 10، ثم 10 − 2 = 8.',
      initialState: { count1: 10, count2: 4 },
      targetState: { count1: 8, count2: 0, total: 8 },
      availableRepresentations: ['ten_frame'],
      defaultRepresentation: 'ten_frame',
      whyExplanation: {
        questionAr: 'كيف فككنا العدد 6؟',
        answerAr: 'فككنا 6 إلى (4 + 2) لنطرح 4 أولاً ونصل للـ 10، ثم نطرح 2 من الـ 10 فنحصل على 8!',
        visualConcept: '14 ➖ 6 🟰 (14 ➖ 4) ➖ 2 🟰 10 ➖ 2 🟰 8',
      },
      walkthroughSteps: [],
      hintAr: 'اطرح 4 لتصل إلى 10، ثم اطرح 2 ليتبقى 8.',
    },
    practiceChallenges: [],
    realWorldApplication: {
      scenarioAr: 'كان في الصندوق 15 قطعة شوكولاتة، وزعت مريم 7 قطع على صديقاتها.',
      character: 'مريم',
      promptAr: 'كم قطعة بقيت؟ 15 − 5 = 10، ثم 10 − 2 = 8!',
      activity: {
        id: 'act_apply_sub_make_ten',
        promptAr: '15 - 7 = 8',
        instructionAr: '15 - 5 = 10، ثم 10 - 2 = 8.',
        initialState: { count1: 10, count2: 5 },
        targetState: { count1: 8, count2: 0, total: 8 },
        availableRepresentations: ['ten_frame'],
        defaultRepresentation: 'ten_frame',
        whyExplanation: {
          questionAr: 'لماذا 8؟',
          answerAr: '15 - 5 = 10، و 10 - 2 = 8 قطع شوكولاتة.',
          visualConcept: '15 ➖ 7 🟰 8',
        },
        walkthroughSteps: [],
        hintAr: '10 - 2 = 8.',
      },
    },
    transferTest: {
      promptAr: 'احسب ذهنياً: 12 − 5 بتكوين العشرة.',
      representation: 'ten_frame',
      activity: {
        id: 'transfer_sub_make_ten',
        promptAr: '12 - 5 = 12 - 2 - 3 = 7',
        instructionAr: '12 - 2 = 10، ثم 10 - 3 = 7.',
        initialState: { count1: 10, count2: 2 },
        targetState: { count1: 7, count2: 0, total: 7 },
        availableRepresentations: ['ten_frame'],
        defaultRepresentation: 'ten_frame',
        whyExplanation: {
          questionAr: 'الناتج 7؟',
          answerAr: '10 - 3 = 7!',
          visualConcept: '12 ➖ 5 🟰 7',
        },
        walkthroughSteps: [],
        hintAr: '10 - 3 = 7.',
      },
    },
    whyExplanation: {
      questionAr: 'لماذا استراتيجية الرجوع للعشرة عبقرية؟',
      answerAr: 'لأنها تحول الطرح الصعب الذي يتجاوز العشرة إلى خطوتين بسيطتين جداً تعتمدان على مكونات الـ 10!',
      interactiveDemoType: 'ten_frame',
    },
  },

  // 7. العلاقة بين الجمع والطرح (مثلث عائلة الحقائق: 8، 5، 13)
  {
    id: 'fact_families',
    titleAr: 'العلاقة بين الجمع والطرح (عائلة الحقائق)',
    subtitleAr: '3 أعداد تصنع 4 جمل رياضية سحرية',
    category: 'subtraction_strategies',
    worldId: 'subtraction',
    icon: '🔺',
    colorTheme: 'from-purple-600 to-pink-600',
    conceptAr: 'الجمع والطرح عمليتان عكسيتان؛ إذا علمت أن (أ + ب = ج)، فبإمكانك فوراً معرفة ناتج (ج − أ = ب) و (ج − ب = أ).',
    objectiveAr: 'أن يربط التلميذ بين جملتي جمع وجملتي طرح لنفس الأعداد الثلاثة (مثل 8، 5، 13).',
    prerequisitesAr: ['حقائق الجمع والطرح حتى 20'],
    supportedRepresentations: ['fact_family', 'objects', 'vertical_equation'],
    storyIntro: {
      characterName: 'ميرو وحراس الهرم الثلاثي',
      scenarioAr: 'في هرم الحقائق الرياضية، يقف العدد الأكبر 13 على القمة، والعددان 8 و 5 في القاعدتين!',
      dialogueAr: 'انظر يا بطل! الجمع يجمع القاعدتين ليعطي القمة (8 + 5 = 13)، والطرح يبدأ من القمة ليأخذ قاعدة ويعطي الأخرى (13 − 5 = 8)!',
      sceneEmoji: '🔺 13 / 8 \\ 5',
    },
    prediction: {
      questionAr: 'إذا عرفت أن 8 + 5 = 13، ما ناتج 13 − 8 بدون أن تعد على أصابعك؟',
      options: [
        { id: 'opt1', textAr: '5 (لأنهم من نفس عائلة الأعداد)', isCorrect: true, explanationAr: 'عبقري! لأن 8 و 5 يكونان 13، فطرح 8 يعطي 5 فوراً!' },
        { id: 'opt2', textAr: '8', isCorrect: false, explanationAr: '13 - 8 = 5.' },
        { id: 'opt3', textAr: '21', isCorrect: false, explanationAr: 'الطرح ينقص ولا يزيد.' },
      ],
    },
    discoveryActivity: {
      id: 'act_discover_fact_family',
      promptAr: 'اكتشف الجمل الأربع لعائلة الأعداد: 8 و 5 و 13.',
      instructionAr: 'اضغط على أزرار الاكتشاف في مثلث الحقائق لتظهر الجمل الرياضية.',
      initialState: { part1: 8, part2: 5, total: 13 },
      targetState: { solved: true },
      availableRepresentations: ['fact_family'],
      defaultRepresentation: 'fact_family',
      whyExplanation: {
        questionAr: 'ليه بنسميها "عائلة الحقائق"؟',
        answerAr: 'لأن هذه الأعداد الثلاثة مرتبطة دائماً معاً! الكل (13) والجزآن (8 و 5). الجمع يجمع الجزأين، والطرح يفصل الكل إلى جزء وباقٍ!',
        visualConcept: '8 ➕ 5 🟰 13 | 5 ➕ 8 🟰 13 | 13 ➖ 8 🟰 5 | 13 ➖ 5 🟰 8',
      },
      walkthroughSteps: [
        { titleAr: 'جمع الجزءين', textAr: '8 + 5 = 13 وأيضاً بالتبديل: 5 + 8 = 13.', visualHintAr: '8 + 5 = 13' },
        { titleAr: 'الطرح من الكل', textAr: '13 − 8 = 5، وأيضاً 13 − 5 = 8!', visualHintAr: '13 - 5 = 8' },
      ],
      hintAr: 'الأعداد الثلاثة تصنع جملتي جمع وجملتي طرح.',
    },
    interactiveLab: {
      id: 'act_lab_fact_family',
      promptAr: 'جرب عائلة الأعداد: 6 و 7 و 13.',
      instructionAr: 'ما ناتج 13 − 7 إذا علمت أن 6 + 7 = 13؟ الناتج هو 6!',
      initialState: { part1: 6, part2: 7, total: 13 },
      targetState: { solved: true },
      availableRepresentations: ['fact_family'],
      defaultRepresentation: 'fact_family',
      whyExplanation: {
        questionAr: 'كيف نتحقق من صحة الطرح بالجمع؟',
        answerAr: 'نتحقق من ناتج الطرح بجمع الناتج مع المطروح، فإذا أعطانا المطروح منه كانت إجابتنا صحيحة 100%!',
        visualConcept: '13 ➖ 7 🟰 6 👈 التحقق: 6 ➕ 7 🟰 13 ✅',
      },
      walkthroughSteps: [],
      hintAr: '13 - 7 = 6.',
    },
    practiceChallenges: [],
    realWorldApplication: {
      scenarioAr: 'مع كريم 12 جنيهاً، اشترى كراسة بـ 7 جنيهات. كم جنيهاً تبقى معه؟',
      character: 'كريم',
      promptAr: 'فكر: 7 + كام = 12؟ إذن 12 − 7 = 5 جنيهات!',
      activity: {
        id: 'act_apply_fact_family',
        promptAr: '12 - 7 = 5',
        instructionAr: 'استخدم حقيقة 7 + 5 = 12.',
        initialState: { part1: 7, part2: 5, total: 12 },
        targetState: { solved: true },
        availableRepresentations: ['fact_family'],
        defaultRepresentation: 'fact_family',
        whyExplanation: {
          questionAr: 'لماذا 5؟',
          answerAr: 'لأن 7 + 5 = 12، إذن 12 - 7 = 5 جنيهات.',
          visualConcept: '12 ➖ 7 🟰 5',
        },
        walkthroughSteps: [],
        hintAr: '7 + 5 = 12.',
      },
    },
    transferTest: {
      promptAr: 'إذا كان 9 + 8 = 17، فما ناتج 17 − 9؟',
      representation: 'fact_family',
      activity: {
        id: 'transfer_fact_family',
        promptAr: '17 - 9 = 8',
        instructionAr: 'الناتج هو الجزء الآخر (8).',
        initialState: { part1: 9, part2: 8, total: 17 },
        targetState: { solved: true },
        availableRepresentations: ['fact_family'],
        defaultRepresentation: 'fact_family',
        whyExplanation: {
          questionAr: 'الناتج 8؟',
          answerAr: 'نعم لأن 9 + 8 = 17!',
          visualConcept: '17 ➖ 9 🟰 8',
        },
        walkthroughSteps: [],
        hintAr: '17 - 9 = 8.',
      },
    },
    whyExplanation: {
      questionAr: 'ما الأهمية العظمى لعائلة الحقائق؟',
      answerAr: 'تمنح الطفل الطلاقة الحسابية، وتجعله لا يرى الطرح كعملية جديدة ومعقدة، بل هو مجرد عكس لعملية الجمع التي يعرفها بالفعل!',
      interactiveDemoType: 'fact_family',
    },
  },

  // 8. القيمة المكانية والتحويل بين الخانات (Place Value: 247)
  {
    id: 'place_value_h_t_o',
    titleAr: 'القيمة المكانية والتحويل بين الخانات',
    subtitleAr: 'المئات والعشرات والآحاد مع قطع دينيز',
    category: 'place_value_regrouping',
    worldId: 'numbers',
    icon: '🧱',
    colorTheme: 'from-amber-600 to-yellow-600',
    conceptAr: 'فهم القيمة المكانية: 1 مائة = 10 عشرات، و 1 عشرة = 10 آحاد، وقيمة الرقم تتحدد بمكانه.',
    objectiveAr: 'أن يفكك التلميذ عدداً مكوناً من ثلاثة أرقام (مثل 247) إلى مئات وعشرات وآحاد ويجري تحويلات بينها.',
    prerequisitesAr: ['الأعداد حتى 100'],
    supportedRepresentations: ['place_value', 'vertical_equation'],
    storyIntro: {
      characterName: 'ميرو في صحراء الأعداد',
      scenarioAr: 'بنى الفراعنة هرم الأرقام من 2 لوح مئات، و 4 أعمدة عشرات، و 7 مكعبات آحاد!',
      dialogueAr: 'يا مهندس المملكة الصغير! ما قيمة هذا العدد؟ 200 + 40 + 7 = 247! وإذا فككنا عمود عشرة، كم مكعب آحاد سيعطينا؟',
      sceneEmoji: '🏜️ 247 = 200 + 40 + 7',
    },
    prediction: {
      questionAr: 'إذا فككنا عمود عشرة واحدة (1 Ten)، كم مكعب آحاد مفرد سنحصل عليه؟',
      options: [
        { id: 'opt1', textAr: '10 مكعبات آحاد بالضبط', isCorrect: true, explanationAr: 'بالتأكيد! عمود العشرة مصنوع من 10 مكعبات آحاد مصفوفة!' },
        { id: 'opt2', textAr: '5 مكعبات فقط', isCorrect: false, explanationAr: 'العشرة الكاملة تحتوي 10 وحدات.' },
        { id: 'opt3', textAr: '100 مكعب', isCorrect: false, explanationAr: '100 مكعب موجودة في لوح المائة الكامل!' },
      ],
    },
    discoveryActivity: {
      id: 'act_discover_place_value',
      promptAr: 'جرب فك عشرة واحدة وشاهد كيف تتحول إلى 10 مكعبات آحاد.',
      instructionAr: 'اضغط على زر (فك 1 عشرة إلى 10 آحاد) في خانة العشرات.',
      initialState: { hundreds: 2, tens: 4, ones: 7 },
      targetState: { total: 247 },
      availableRepresentations: ['place_value'],
      defaultRepresentation: 'place_value',
      whyExplanation: {
        questionAr: 'ليه نظام الأعداد بتاعنا اسمه "النظام العشري"؟',
        answerAr: 'لأن كل خانة تبنى على أساس الرقم 10! 10 آحاد تكون عشرة، و 10 عشرات تكون مائة، و 10 مئات تكون ألفاً!',
        visualConcept: '10 الآحاد 🟰 1 عشرة | 10 العشرات 🟰 1 مائة',
      },
      walkthroughSteps: [
        { titleAr: 'الآحاد (Ones)', textAr: '7 مكعبات قيمتها 7.', visualHintAr: '7' },
        { titleAr: 'العشرات (Tens)', textAr: '4 أعمدة قيمتها 40.', visualHintAr: '40' },
        { titleAr: 'المئات (Hundreds)', textAr: 'لوحان قيمتهما 200.', visualHintAr: '200' },
        { titleAr: 'التحويل المرن', textAr: 'يمكننا فك عشرة إلى 10 آحاد، وتظل القيمة الكلية 247 دون تغيير!', visualHintAr: '247' },
      ],
      hintAr: 'اضغط على أزرار الفك والتركيب لمشاهدة السحر الرياضي.',
    },
    interactiveLab: {
      id: 'act_lab_place_value',
      promptAr: 'جمع 10 مكعبات آحاد لتصنع منها عمود عشرة واحدة.',
      instructionAr: 'اضغط على زر تجميع 10 مكعبات عندما تصبح الآحاد 10 أو أكثر.',
      initialState: { hundreds: 1, tens: 2, ones: 14 },
      targetState: { hundreds: 1, tens: 3, ones: 4, total: 134 },
      availableRepresentations: ['place_value'],
      defaultRepresentation: 'place_value',
      whyExplanation: {
        questionAr: 'ليه لازم نجمع الـ 10 آحاد في عشرة واحدة؟',
        answerAr: 'لأن خانة الآحاد لا تقبل كتابة أكثر من رقم واحد (من 0 إلى 9). فإذا وصلت 10، تنتقل فوراً كعشرة واحدة إلى خانة العشرات!',
        visualConcept: '14 آحاد 🟰 1 عشرة جديدة ➕ 4 آحاد متبقية',
      },
      walkthroughSteps: [],
      hintAr: 'اضغط زر التجميع لتحويل 10 مكعبات إلى عمود عشرة.',
    },
    practiceChallenges: [],
    realWorldApplication: {
      scenarioAr: 'في البنك، كان مع سارة ورقتان فئة 100 جنيه، و 5 ورقات فئة 10 جنيهات، و 3 جنيهات فكة.',
      character: 'سارة',
      promptAr: 'ما المبلغ الكلي مع سارة؟ 200 + 50 + 3 = 253 جنيهاً.',
      activity: {
        id: 'act_apply_place_value',
        promptAr: '2 مئات + 5 عشرات + 3 آحاد = 253',
        instructionAr: 'حدد المبلغ الإجمالي.',
        initialState: { hundreds: 2, tens: 5, ones: 3 },
        targetState: { total: 253 },
        availableRepresentations: ['place_value'],
        defaultRepresentation: 'place_value',
        whyExplanation: {
          questionAr: 'لماذا 253؟',
          answerAr: 'المئات 200 + العشرات 50 + الآحاد 3 = 253 جنيهاً.',
          visualConcept: '200 ➕ 50 ➕ 3 🟰 253',
        },
        walkthroughSteps: [],
        hintAr: '200 + 50 + 3 = 253.',
      },
    },
    transferTest: {
      promptAr: 'ما قيمة الرقم 4 في العدد 348؟',
      representation: 'place_value',
      activity: {
        id: 'transfer_place_value',
        promptAr: 'قيمة الرقم 4 في خانة العشرات هي 40',
        instructionAr: '4 عشرات = 40.',
        initialState: { hundreds: 3, tens: 4, ones: 8 },
        targetState: { total: 348 },
        availableRepresentations: ['place_value'],
        defaultRepresentation: 'place_value',
        whyExplanation: {
          questionAr: 'ليه قيمته 40 مش 4؟',
          answerAr: 'لأنه يسكن في خانة العشرات، و 4 عشرات = 40!',
          visualConcept: '4 في العشرات 🟰 40',
        },
        walkthroughSteps: [],
        hintAr: 'الرقم في خانة العشرات قيمته 40.',
      },
    },
    whyExplanation: {
      questionAr: 'ما الفرق بين القيمة المكانية وقيمة الرقم؟',
      answerAr: 'القيمة المكانية هي اسم الخانة (آحاد، عشرات، مئات). أما قيمة الرقم فهي كم يساوي بالعدد (مثلاً 5 في العشرات تساوي 50)!',
      interactiveDemoType: 'place_value',
    },
  },

  // 9. الجمع الرأسي مع إعادة التجميع (27 + 18 = 45)
  {
    id: 'add_vertical_regroup',
    titleAr: 'الجمع الرأسي مع إعادة التجميع',
    subtitleAr: 'حل المسألة النموذجية 27 + 18 خطوة بخطوة',
    category: 'place_value_regrouping',
    worldId: 'addition',
    icon: '🏗️',
    colorTheme: 'from-amber-600 to-emerald-600',
    conceptAr: 'عند جمع الآحاد ويكون الناتج 10 أو أكثر، نضع رقم الآحاد في الناتج ونعيد تجميع العشرة (الحمل بـ 1) في خانة العشرات.',
    objectiveAr: 'أن يجمع التلميذ 27 + 18 رأسياً: 7 + 8 = 15 (5 في الآحاد و 1 عشرة مضافة للعشرات)، ثم 1 + 2 + 1 = 4 عشرات -> 45.',
    prerequisitesAr: ['الجمع حتى 20', 'القيمة المكانية'],
    supportedRepresentations: ['vertical_equation', 'place_value'],
    storyIntro: {
      characterName: 'ميرو وبناء البرج العظيم',
      scenarioAr: 'يحتاج برج القلعة إلى 27 حجراً ذهبياً و 18 حجراً فيروزياً. نريد حساب المجموع الكلي لبناء البرج!',
      dialogueAr: 'يا بطل! سنبدأ بجمع الآحاد أولاً (7 + 8 = 15). هل نكتب 15 كلها في خانة الآحاد؟ لا! نضع 5 ونرفع العشرة كحجر سحري جديد فوق العشرات!',
      sceneEmoji: '🧱 27 ➕ 18 🟰 45',
    },
    prediction: {
      questionAr: 'عند جمع 7 + 8 نحصل على 15. هل يمكن لخانة الآحاد أن تحتفظ برقمين (15)؟',
      options: [
        { id: 'opt1', textAr: 'لا، نضع 5 في الآحاد ونعيد تجميع 1 عشرة فوق خانة العشرات', isCorrect: true, explanationAr: 'ممتاز! كل خانة تسع رقماً واحداً فقط من 0 إلى 9!' },
        { id: 'opt2', textAr: 'نعم، نكتب 15 في الآحاد', isCorrect: false, explanationAr: 'خانة الآحاد تسع رقماً واحداً فقط.' },
        { id: 'opt3', textAr: 'نحذف الواحد ونهمله', isCorrect: false, explanationAr: 'لا نهمل أي رقم، بل ننقله لخانته الصحيحة!' },
      ],
    },
    discoveryActivity: {
      id: 'act_discover_add_regroup',
      promptAr: 'شاهد وجرب حل 27 + 18 في الخوارزمية الرأسية.',
      instructionAr: 'اجمع الآحاد (7 + 8)، ضع 1 في مربع التجميع، ثم اجمع العشرات.',
      initialState: { num1: 27, num2: 18, op: 'add' },
      targetState: { result: 45 },
      availableRepresentations: ['vertical_equation', 'place_value'],
      defaultRepresentation: 'vertical_equation',
      whyExplanation: {
        questionAr: 'ليه بنرفع 1 فوق خانة العشرات؟ (ما معنى الحمل؟)',
        answerAr: 'لأن الـ 15 تتكون من 5 آحاد و 1 عشرة كاملة! وبما أن الخانة المجاورة هي خانة العشرات، فالواحد مكانه الحقيقي هناك!',
        visualConcept: '7 ➕ 8 🟰 15 🟰 5 آحاد ➕ 1 عشرة منقولة ⬆️',
      },
      walkthroughSteps: [
        { titleAr: 'الخطوة 1: اجمع الآحاد', textAr: '7 + 8 = 15. نكتب 5 في خانة الآحاد تحت الخط.', visualHintAr: '7 + 8 = 15' },
        { titleAr: 'الخطوة 2: إعادة التجميع', textAr: 'نرفع 1 عشرة فوق خانة العشرات في المربع الصغير.', visualHintAr: '⬆️ 1 عشرة' },
        { titleAr: 'الخطوة 3: اجمع العشرات', textAr: '1 (المنقولة) + 2 + 1 = 4 عشرات. نكتب 4.', visualHintAr: '1 + 2 + 1 = 4' },
        { titleAr: 'الناتج النهائي', textAr: 'الناتج هو 45 بالضبط!', visualHintAr: '45' },
      ],
      hintAr: '7 + 8 = 15، اكتب 5 في الآحاد و 1 فوق العشرات، ثم 1 + 2 + 1 = 4.',
    },
    interactiveLab: {
      id: 'act_lab_add_regroup',
      promptAr: 'حل المسألة 36 + 27 رأسياً.',
      instructionAr: '6 + 7 = 13 (نضع 3 ونعيد تجميع 1)، ثم 1 + 3 + 2 = 6 عشرات -> 63.',
      initialState: { num1: 36, num2: 27, op: 'add' },
      targetState: { result: 63 },
      availableRepresentations: ['vertical_equation', 'place_value'],
      defaultRepresentation: 'vertical_equation',
      whyExplanation: {
        questionAr: 'ما الخطأ الشائع الذي يجب تجنبه؟',
        answerAr: 'الخطأ هو نسيان إضافة العشرة الجديدة (1) عند جمع العشرات! دائماً قل لنفسك: 1 + 3 + 2 = 6!',
        visualConcept: 'لا تنس الـ 1 المنقولة! ⭐',
      },
      walkthroughSteps: [],
      hintAr: '6 + 7 = 13 (اكتب 3 وارفع 1)، ثم 1 + 3 + 2 = 6.',
    },
    practiceChallenges: [],
    realWorldApplication: {
      scenarioAr: 'اشترى مروان قميصاً بـ 48 جنيهاً وقبعة بـ 25 جنيهاً.',
      character: 'مروان',
      promptAr: 'ما المبلغ الكلي الذي دفعه مروان؟ 48 + 25 = 73 جنيهاً.',
      activity: {
        id: 'act_apply_add_regroup',
        promptAr: '48 + 25 = 73',
        instructionAr: '8 + 5 = 13 (3 ونعيد تجميع 1)، 1 + 4 + 2 = 7.',
        initialState: { num1: 48, num2: 25, op: 'add' },
        targetState: { result: 73 },
        availableRepresentations: ['vertical_equation'],
        defaultRepresentation: 'vertical_equation',
        whyExplanation: {
          questionAr: 'لماذا 73؟',
          answerAr: '8 + 5 = 13، و 1 + 4 + 2 = 7 عشرات -> 73 جنيهاً.',
          visualConcept: '48 ➕ 25 🟰 73',
        },
        walkthroughSteps: [],
        hintAr: '8 + 5 = 13، اكتب 3 وارفع 1 للعشرات.',
      },
    },
    transferTest: {
      promptAr: 'حل المسألة: 59 + 24 = ؟',
      representation: 'vertical_equation',
      activity: {
        id: 'transfer_add_regroup',
        promptAr: '59 + 24 = 83',
        instructionAr: '9 + 4 = 13، 1 + 5 + 2 = 8.',
        initialState: { num1: 59, num2: 24, op: 'add' },
        targetState: { result: 83 },
        availableRepresentations: ['vertical_equation'],
        defaultRepresentation: 'vertical_equation',
        whyExplanation: {
          questionAr: 'الناتج 83؟',
          answerAr: '9 + 4 = 13، 1 + 5 + 2 = 8 -> 83!',
          visualConcept: '59 ➕ 24 🟰 83',
        },
        walkthroughSteps: [],
        hintAr: '9 + 4 = 13، ثم 1 + 5 + 2 = 8.',
      },
    },
    whyExplanation: {
      questionAr: 'لماذا نسميها "إعادة تجميع" وليس فقط "حمل"؟',
      answerAr: 'لأننا نجمع 10 مكعبات آحاد صغيرة ونشكل منها مجموعة جديدة تسمى "عشرة واحدة"، فنحن نعيد تجميعها في شكل حزمة جديدة!',
      interactiveDemoType: 'place_value',
    },
  },

  // 10. الطرح الرأسي مع إعادة التسمية (42 - 18 = 24)
  {
    id: 'sub_vertical_regroup',
    titleAr: 'الطرح الرأسي مع إعادة التسمية (الاستلاف)',
    subtitleAr: 'حل المسألة النموذجية 42 − 18 بفك العشرات',
    category: 'place_value_regrouping',
    worldId: 'subtraction',
    icon: '✂️',
    colorTheme: 'from-rose-600 to-red-700',
    conceptAr: 'عندما يكون رقم الآحاد في المطروح منه أصغر من المطروح، لا نعكس الطرح! بل نفك عشرة واحدة (إعادة تسمية) فتصبح 10 آحاد تضاف للآحاد.',
    objectiveAr: 'أن يطرح التلميذ 42 − 18 بفك 1 عشرة من 4 لتصبح 3 عشرات، وتصبح الآحاد 12، ثم 12 − 8 = 4 و 3 − 1 = 2 -> 24.',
    prerequisitesAr: ['الطرح حتى 20', 'القيمة المكانية'],
    supportedRepresentations: ['vertical_equation', 'place_value'],
    storyIntro: {
      characterName: 'ميرو وسوق البهارات',
      scenarioAr: 'مع التاجر 42 كيساً من البهارات. باع منها 18 كيساً. نريد معرفة الباقي بدقة!',
      dialogueAr: 'انظر للآحاد: نريد طرح 8 من 2. لكن 2 أصغر من 8 ولا تكفي! ماذا نفعل؟ نذهب لخانة العشرات ونفك عشرة واحدة، فيصبح معنا 12 آحاد!',
      sceneEmoji: '🛍️ 42 ➖ 18 🟰 24',
    },
    prediction: {
      questionAr: 'في المسألة 42 − 18، الآحاد هي 2 − 8. هل يجوز أن نقول 8 − 2 = 6؟',
      options: [
        { id: 'opt1', textAr: 'خطأ كبير! لا يجوز عكس الأرقام، بل يجب فك عشرة لزيادة الآحاد', isCorrect: true, explanationAr: 'أحسنت التمييز! الطرح ليس إبدالياً، والمطروح منه في الأعلى دائماً!' },
        { id: 'opt2', textAr: 'نعم يجوز لأن 8 − 2 سهلة', isCorrect: false, explanationAr: 'انتبه! هذا خطأ شائع جداً. لا نطرح الصغير من الكبير بالعكس!' },
        { id: 'opt3', textAr: 'نكتب صفر في الآحاد', isCorrect: false, explanationAr: 'يجب إعادة تسمية عشرة.' },
      ],
    },
    discoveryActivity: {
      id: 'act_discover_sub_regroup',
      promptAr: 'حل 42 − 18: اضغط على زر فك عشرة لتتحول الـ 2 إلى 12 والـ 4 إلى 3.',
      instructionAr: 'ثم اطرح الآحاد (12 − 8 = 4) والعشرات (3 − 1 = 2).',
      initialState: { num1: 42, num2: 18, op: 'subtract' },
      targetState: { result: 24 },
      availableRepresentations: ['vertical_equation', 'place_value'],
      defaultRepresentation: 'vertical_equation',
      whyExplanation: {
        questionAr: 'ليه بنسميها "إعادة تسمية" مش مجرد استلاف؟',
        answerAr: 'لأننا لم نأخذ شيئاً من خارج العدد! الـ 42 كانت: (4 عشرات و 2 آحاد)، وأعدنا تسميتها إلى: (3 عشرات و 12 آحاد)! قيمتها ظلت 42 كما هي!',
        visualConcept: '4 عشرات ➕ 2 آحاد 🟰 3 عشرات ➕ 12 آحاد (كلتاهما = 42)!',
      },
      walkthroughSteps: [
        { titleAr: 'الخطوة 1: فحص الآحاد', textAr: '2 − 8 لا تجوز لأن 2 أصغر من 8.', visualHintAr: '2 < 8' },
        { titleAr: 'الخطوة 2: فك عشرة واحدة', textAr: 'نشطب 4 عشرات لتصبح 3، ونضيف 10 إلى 2 لتصبح 12.', visualHintAr: '4 ➡️ 3 | 2 ➡️ 12' },
        { titleAr: 'الخطوة 3: اطرح الآحاد', textAr: '12 − 8 = 4. نكتب 4 في الآحاد.', visualHintAr: '12 - 8 = 4' },
        { titleAr: 'الخطوة 4: اطرح العشرات', textAr: '3 − 1 = 2. نكتب 2 في العشرات.', visualHintAr: '3 - 1 = 2' },
        { titleAr: 'الناتج النهائي', textAr: 'الباقي هو 24 كيساً!', visualHintAr: '24' },
      ],
      hintAr: 'فك عشرة: 4 تصبح 3، و 2 تصبح 12، ثم 12 - 8 = 4 و 3 - 1 = 2.',
    },
    interactiveLab: {
      id: 'act_lab_sub_regroup',
      promptAr: 'حل المسألة 53 − 26 رأسياً.',
      instructionAr: '3 أصغر من 6، فك عشرة من 5 لتصبح 4، وتصبح 3 هي 13. 13 − 6 = 7، و 4 − 2 = 2 -> 27.',
      initialState: { num1: 53, num2: 26, op: 'subtract' },
      targetState: { result: 27 },
      availableRepresentations: ['vertical_equation', 'place_value'],
      defaultRepresentation: 'vertical_equation',
      whyExplanation: {
        questionAr: 'كيف نتحقق بالجمع؟',
        answerAr: 'نجمع الناتج 27 + المطروح 26 = 53! إجابة سليمة!',
        visualConcept: '27 ➕ 26 🟰 53 ✅',
      },
      walkthroughSteps: [],
      hintAr: '13 - 6 = 7، و 4 - 2 = 2 -> 27.',
    },
    practiceChallenges: [],
    realWorldApplication: {
      scenarioAr: 'كان في بستان البرتقال 61 شجرة مثمرة، قطف الفلاح ثمار 35 شجرة.',
      character: 'عم أحمد',
      promptAr: 'كم شجرة بقيت لم تقطف بعد؟ 61 − 35 = 26 شجرة.',
      activity: {
        id: 'act_apply_sub_regroup',
        promptAr: '61 - 35 = 26',
        instructionAr: '11 - 5 = 6، و 5 - 3 = 2.',
        initialState: { num1: 61, num2: 35, op: 'subtract' },
        targetState: { result: 26 },
        availableRepresentations: ['vertical_equation'],
        defaultRepresentation: 'vertical_equation',
        whyExplanation: {
          questionAr: 'لماذا 26؟',
          answerAr: '11 - 5 = 6 آحاد، و 5 - 3 = 2 عشرات -> 26 شجرة.',
          visualConcept: '61 ➖ 35 🟰 26',
        },
        walkthroughSteps: [],
        hintAr: 'فك عشرة: 1 يصبح 11، و 6 تصبح 5.',
      },
    },
    transferTest: {
      promptAr: 'حل المسألة: 74 − 38 = ؟',
      representation: 'vertical_equation',
      activity: {
        id: 'transfer_sub_regroup',
        promptAr: '74 - 38 = 36',
        instructionAr: '14 - 8 = 6، و 6 - 3 = 3.',
        initialState: { num1: 74, num2: 38, op: 'subtract' },
        targetState: { result: 36 },
        availableRepresentations: ['vertical_equation'],
        defaultRepresentation: 'vertical_equation',
        whyExplanation: {
          questionAr: 'الناتج 36؟',
          answerAr: 'نعم لأن 14 - 8 = 6، و 6 - 3 = 3 -> 36!',
          visualConcept: '74 ➖ 38 🟰 36',
        },
        walkthroughSteps: [],
        hintAr: '14 - 8 = 6، ثم 6 - 3 = 3.',
      },
    },
    whyExplanation: {
      questionAr: 'ما أعظم فائدة لتعلم إعادة التسمية في الطرح؟',
      answerAr: 'تحمي الطفل مدى الحياة من خطأ "طرح الصغير من الكبير" وتمنحه فهماً متيناً لقيمة الأعداد ومرونتها!',
      interactiveDemoType: 'place_value',
    },
  },

  // 11. المسائل الكلامية التفاعلية (Story Problems Lab)
  {
    id: 'story_problem_lab',
    titleAr: 'مختبر المسائل الكلامية الحياتية',
    subtitleAr: 'حول القصة إلى مشهد بصري ثم إلى معادلة',
    category: 'story_problems',
    worldId: 'mixed',
    icon: '📖',
    colorTheme: 'from-pink-500 to-rose-600',
    conceptAr: 'فهم المسألة الكلامية يبدأ بتخيل الحدث ورؤية العناصر تدخل أو تخرج، وتحديد العملية (+ أو −) قبل الحساب.',
    objectiveAr: 'أن يمثل التلميذ المسألة الكلامية بموقف بصري ورموز رياضية صحيحة.',
    prerequisitesAr: ['الجمع والطرح حتى 20'],
    supportedRepresentations: ['objects', 'vertical_equation'],
    storyIntro: {
      characterName: 'ميرو في واحة التفاح',
      scenarioAr: 'كان في سلة ميرو 12 تفاحة حمراء طازجة. دخل صديقه الأرنب وأهداه 7 تفاحات أخرى!',
      dialogueAr: 'شاهد المشهد يا بطل! التفاحات دخلت وزادت في السلة! هل هذه عملية جمع (+) أم طرح (−)؟',
      sceneEmoji: '🧺 12 تفاحة ➕ 7 تفاحات جديدة',
    },
    prediction: {
      questionAr: 'عندما يُعطى ميرو تفاحات إضافية، هل نستخدم الجمع أم الطرح؟',
      options: [
        { id: 'opt1', textAr: 'الجمع (+) لأن عدد التفاحات زاد!', isCorrect: true, explanationAr: 'صحيح! الزيادة والإضافة تعني الجمع!' },
        { id: 'opt2', textAr: 'الطرح (−)', isCorrect: false, explanationAr: 'الطرح عندما ينقص الشيء أو نأكل منه!' },
      ],
    },
    discoveryActivity: {
      id: 'act_discover_story_problem',
      promptAr: 'مع ميرو 12 تفاحة، وجد 7 أخرى. كم تفاحة مع ميرو الآن؟',
      instructionAr: 'اجمع: 12 + 7 = 19 تفاحة.',
      initialState: { start: 12, added: 7 },
      targetState: { total: 19 },
      availableRepresentations: ['objects', 'vertical_equation'],
      defaultRepresentation: 'objects',
      whyExplanation: {
        questionAr: 'كيف نميز بين مسائل الجمع ومسائل الطرح؟',
        answerAr: 'كلمات مثل (معاً، المجموع، أضاف، اشترى، كسب) تدل على الجمع (+). وكلمات مثل (بقي، خسر، أنفق، طار، أكل) تدل على الطرح (−)!',
        visualConcept: '➕ زاد / أضاف | ➖ نقص / أكل / بقي',
      },
      walkthroughSteps: [
        { titleAr: 'افهم القصة', textAr: 'البداية: 12 تفاحة. الإضافة: 7 تفاحات.', visualHintAr: '12 + 7' },
        { titleAr: 'حدد العملية', textAr: 'العملية هي الجمع (+).', visualHintAr: '+' },
        { titleAr: 'احسب الناتج', textAr: '12 + 7 = 19 تفاحة لذيذة!', visualHintAr: '19' },
      ],
      hintAr: '12 + 7 = 19.',
    },
    interactiveLab: {
      id: 'act_lab_story_problem',
      promptAr: 'كان في بركة الماء 18 بطة، طارت منها 6 بطات. كم بطة بقيت؟',
      instructionAr: 'حدد العملية: نقصت البطات إذن طرح: 18 − 6 = 12 بطة.',
      initialState: { start: 18, removed: 6 },
      targetState: { total: 12 },
      availableRepresentations: ['objects', 'vertical_equation'],
      defaultRepresentation: 'objects',
      whyExplanation: {
        questionAr: 'ليه طرحنا في مسألة البطات؟',
        answerAr: 'لأن البطات طارت وغادرت البركة، والعدد المتبقي أصبح أقل من 18!',
        visualConcept: '18 ➖ 6 🟰 12 بطة',
      },
      walkthroughSteps: [],
      hintAr: '18 - 6 = 12.',
    },
    practiceChallenges: [],
    realWorldApplication: {
      scenarioAr: 'وفرت نور 35 جنيهاً في الأسبوع الأول، ووفرت 24 جنيهاً في الأسبوع الثاني.',
      character: 'نور',
      promptAr: 'ما مجموع ما وفرته نور في الأسبوعين؟ 35 + 24 = 59 جنيهاً.',
      activity: {
        id: 'act_apply_story_problem',
        promptAr: '35 + 24 = 59',
        instructionAr: 'اجمع الآحاد (5+4=9) والعشرات (3+2=5).',
        initialState: { num1: 35, num2: 24, op: 'add' },
        targetState: { result: 59 },
        availableRepresentations: ['vertical_equation'],
        defaultRepresentation: 'vertical_equation',
        whyExplanation: {
          questionAr: 'لماذا 59؟',
          answerAr: '35 + 24 = 59 جنيهاً مجموع مدخرات نور.',
          visualConcept: '35 ➕ 24 🟰 59',
        },
        walkthroughSteps: [],
        hintAr: '35 + 24 = 59.',
      },
    },
    transferTest: {
      promptAr: 'مع شادي 48 بالونة، فرقعت منها 15 بالونة. كم بالونة بقيت؟',
      representation: 'vertical_equation',
      activity: {
        id: 'transfer_story_problem',
        promptAr: '48 - 15 = 33 بالونة',
        instructionAr: '8 - 5 = 3، و 4 - 1 = 3.',
        initialState: { num1: 48, num2: 15, op: 'subtract' },
        targetState: { result: 33 },
        availableRepresentations: ['vertical_equation'],
        defaultRepresentation: 'vertical_equation',
        whyExplanation: {
          questionAr: 'الناتج 33؟',
          answerAr: '48 - 15 = 33 بالونة سليمة.',
          visualConcept: '48 ➖ 15 🟰 33',
        },
        walkthroughSteps: [],
        hintAr: '48 - 15 = 33.',
      },
    },
    whyExplanation: {
      questionAr: 'لماذا نحول المسائل الكلامية لمشاهد تفاعلية؟',
      answerAr: 'لأن الطفل يتعلم الرياضيات ليستخدمها في الحياة الواقعية، وعندما يرى الموقف يتخيل المعنى الحقيقي للجمع والطرح!',
      interactiveDemoType: 'objects',
    },
  },

  // 12. لوحة الـ 120 واكتشاف الأنماط (37 + 10 = 47, 37 - 10 = 27)
  {
    id: 'chart_120_patterns',
    titleAr: 'لوحة الـ 120 واكتشاف الأنماط',
    subtitleAr: 'الحركة الرأسية والأفقية وقواعد الجيران',
    category: 'number_patterns',
    worldId: 'numbers',
    icon: '🔢',
    colorTheme: 'from-teal-500 to-emerald-700',
    conceptAr: 'على لوحة الـ 120: النزول صفاً لأسفل يزيد 10 (+10)، والصعود لأعلى ينقص 10 (−10)، والتحرك أفقياً يغير الآحاد (±1).',
    objectiveAr: 'أن يحدد التلميذ جيران أي عدد على لوحة الـ 120 (+1, −1, +10, −10) ذهنياً.',
    prerequisitesAr: ['العد حتى 100'],
    supportedRepresentations: ['chart_120'],
    storyIntro: {
      characterName: 'ميرو على بساط الأرقام',
      scenarioAr: 'هبط ميرو على الخانة رقم 37 على لوحة الـ 120 السحرية!',
      dialogueAr: 'يا كاشف الأسرار! إذا نزلنا خطوة واحدة للأسفل، سنصل إلى 47! وإذا صعدنا خطوة للأعلى، سنصل إلى 27! ما الذي يتغير؟ خانة العشرات فقط!',
      sceneEmoji: '⬆️ 27 | 📍 37 | ⬇️ 47',
    },
    prediction: {
      questionAr: 'إذا كنا نقف عند العدد 37 ونزلنا صفاً واحداً لأسفل، ما العدد الذي سنصل إليه؟',
      options: [
        { id: 'opt1', textAr: '47 (لأن النزول لأسفل يعني إضافة 10 كاملة)', isCorrect: true, explanationAr: 'صحيح تماماً! 37 + 10 = 47!' },
        { id: 'opt2', textAr: '38', isCorrect: false, explanationAr: '38 هي خطوة واحدة للأمام (+1) وليس صفاً كاملاً!' },
        { id: 'opt3', textAr: '27', isCorrect: false, explanationAr: '27 عند الصعود لأعلى (−10).' },
      ],
    },
    discoveryActivity: {
      id: 'act_discover_chart_120',
      promptAr: 'جرب تحريك ميرو عند العدد 37 واكتشف جيرانه الأربعة.',
      instructionAr: 'اضغط على +10 و −10 و +1 و −1 وشاهد النمط.',
      initialState: { current: 37 },
      targetState: { current: 47 },
      availableRepresentations: ['chart_120'],
      defaultRepresentation: 'chart_120',
      whyExplanation: {
        questionAr: 'ليه النزول صف لأسفل بيزود 10؟',
        answerAr: 'لأن كل صف في اللوحة يحتوي على 10 أعداد بالضبط! فعندما ننتقل للصف التالي، نكون قد قفزنا 10 أعداد كاملة!',
        visualConcept: 'كل صف 🟰 10 أعداد 👈 الصف التالي = +10',
      },
      walkthroughSteps: [
        { titleAr: 'الجار العلوي (−10)', textAr: '37 − 10 = 27 (العشرات صغرت 1).', visualHintAr: '27' },
        { titleAr: 'الجار السفلي (+10)', textAr: '37 + 10 = 47 (العشرات زادت 1).', visualHintAr: '47' },
        { titleAr: 'الجار السابق (−1)', textAr: '37 − 1 = 36.', visualHintAr: '36' },
        { titleAr: 'الجار اللاحق (+1)', textAr: '37 + 1 = 38.', visualHintAr: '38' },
      ],
      hintAr: 'استخدم أزرار الأسهم في اللوحة.',
    },
    interactiveLab: {
      id: 'act_lab_chart_120',
      promptAr: 'قف عند العدد 54 وتحرك ليصل إلى 64.',
      instructionAr: 'اضغط على زر +10.',
      initialState: { current: 54 },
      targetState: { current: 64 },
      availableRepresentations: ['chart_120'],
      defaultRepresentation: 'chart_120',
      whyExplanation: {
        questionAr: 'ماذا نلاحظ في الآحاد؟',
        answerAr: 'الآحاد ظلت 4 في العددين (54 و 64) دون أي تغيير!',
        visualConcept: '54 ➕ 10 🟰 64',
      },
      walkthroughSteps: [],
      hintAr: '54 + 10 = 64.',
    },
    practiceChallenges: [],
    realWorldApplication: {
      scenarioAr: 'يقف قطار المترو عند المحطة 43، بعد 10 محطات أين سيصل؟',
      character: 'سائق القطار',
      promptAr: '43 + 10 = 53.',
      activity: {
        id: 'act_apply_chart_120',
        promptAr: '43 + 10 = 53',
        instructionAr: 'زد العشرات 1 تصبح 53.',
        initialState: { current: 43 },
        targetState: { current: 53 },
        availableRepresentations: ['chart_120'],
        defaultRepresentation: 'chart_120',
        whyExplanation: {
          questionAr: 'لماذا 53؟',
          answerAr: '43 + 10 = 53.',
          visualConcept: '43 ➕ 10 🟰 53',
        },
        walkthroughSteps: [],
        hintAr: '43 + 10 = 53.',
      },
    },
    transferTest: {
      promptAr: 'ما هو العدد الذي يقع مباشرة فوق العدد 82 على لوحة الـ 120؟',
      representation: 'chart_120',
      activity: {
        id: 'transfer_chart_120',
        promptAr: '82 - 10 = 72',
        instructionAr: 'اطرح 10 -> 72.',
        initialState: { current: 82 },
        targetState: { current: 72 },
        availableRepresentations: ['chart_120'],
        defaultRepresentation: 'chart_120',
        whyExplanation: {
          questionAr: 'العدد 72؟',
          answerAr: 'نعم لأن الصف الأعلى ينقص 10: 82 - 10 = 72!',
          visualConcept: '82 ➖ 10 🟰 72',
        },
        walkthroughSteps: [],
        hintAr: '82 - 10 = 72.',
      },
    },
    whyExplanation: {
      questionAr: 'لماذا لوحة الـ 120 أداة أساسية في المنهج المصري؟',
      answerAr: 'لأنها تحول الأرقام المجردة إلى خريطة جغرافية واضحة للعين، يستكشف فيها الطفل الأنماط بنفسه!',
      interactiveDemoType: 'chart_120',
    },
  },

  // 13. قراءة الساعة التفاعلية (الساعة تماماً والنصف)
  {
    id: 'time_interactive',
    titleAr: 'مختبر قراءة الوقت بالساعة',
    subtitleAr: 'العقرب القصير للساعات والعقرب الطويل للدقائق',
    category: 'time_and_measurement',
    worldId: 'time',
    icon: '⏰',
    colorTheme: 'from-cyan-500 to-blue-600',
    conceptAr: 'الساعة التناظرية: العقرب القصير يشير للساعة، والعقرب الطويل يشير للدقائق (عند 12 = تماماً :00، وعند 6 = ونصف :30).',
    objectiveAr: 'أن يقرأ التلميذ ويضبط الساعة تماماً وبالنصف: 07:30 (السابعة والنصف).',
    prerequisitesAr: ['قراءة الأعداد من 1 إلى 12'],
    supportedRepresentations: ['clock'],
    storyIntro: {
      characterName: 'طائر الساعة الذهبي',
      scenarioAr: 'حان موعد انطلاق قارب بطل النيل في تمام الساعة السابعة والنصف صباحاً (07:30)!',
      dialogueAr: 'اضبط عقارب الساعة يا بطل: اجعل العقرب القصير عند 7 والعقرب الطويل عند 6 (والنصف)!',
      sceneEmoji: '⏰ 07:30 (السابعة والنصف)',
    },
    prediction: {
      questionAr: 'عندما يشير العقرب الكبير (الطويل) إلى الرقم 6، ماذا يعني ذلك؟',
      options: [
        { id: 'opt1', textAr: 'يعني نصف ساعة (30 دقيقة)', isCorrect: true, explanationAr: 'صحيح! لأن الساعة الكاملة 60 دقيقة ونصفها 30 دقيقة عند الرقم 6!' },
        { id: 'opt2', textAr: 'يعني الساعة 6 تماماً', isCorrect: false, explanationAr: 'العقرب الصغير هو الذي يحدد رقم الساعة!' },
      ],
    },
    discoveryActivity: {
      id: 'act_discover_clock',
      promptAr: 'اضبط الساعة على السابعة والنصف (07:30).',
      instructionAr: 'اختر الساعة 7 واضغط على زر (والنصف :30).',
      initialState: { hours: 4, minutes: 0 },
      targetState: { hours: 7, minutes: 30 },
      availableRepresentations: ['clock'],
      defaultRepresentation: 'clock',
      whyExplanation: {
        questionAr: 'ليه الرقم 6 في الدقائق معناه 30 دقيقة؟',
        answerAr: 'لأن الدورة الكاملة للعقرب الكبير تساوي 60 دقيقة. وعندما يقطع نصف الدائرة ويصل إلى 6، يكون قد قطع نصف الوقت: 30 دقيقة!',
        visualConcept: 'نصف دائرة 🟰 30 دقيقة 🟰 نصف ساعة',
      },
      walkthroughSteps: [
        { titleAr: 'العقرب القصير (الساعات)', textAr: 'يشير إلى الرقم 7.', visualHintAr: '7' },
        { titleAr: 'العقرب الطويل (الدقائق)', textAr: 'يشير إلى 6 (30 دقيقة).', visualHintAr: ':30' },
        { titleAr: 'الوقت معاً', textAr: 'السابعة والنصف (07:30)!', visualHintAr: '07:30' },
      ],
      hintAr: 'اختر الساعة 7 ثم اضغط على زر والنصف (:30).',
    },
    interactiveLab: {
      id: 'act_lab_clock',
      promptAr: 'اضبط الساعة على العاشرة تماماً (10:00).',
      instructionAr: 'اختر الساعة 10 والدقائق تماماً (:00).',
      initialState: { hours: 7, minutes: 30 },
      targetState: { hours: 10, minutes: 0 },
      availableRepresentations: ['clock'],
      defaultRepresentation: 'clock',
      whyExplanation: {
        questionAr: 'ماذا يعني العقرب عند 12؟',
        answerAr: 'يعني بداية ساعة جديدة كاملة (00 دقيقة) وتسمى "تماماً"!',
        visualConcept: '12 = تماماً (:00)',
      },
      walkthroughSteps: [],
      hintAr: 'اختر 10 وتماماً.',
    },
    practiceChallenges: [],
    realWorldApplication: {
      scenarioAr: 'يبدأ الطابور الصباحي في المدرسة في الساعة الثامنة تماماً (08:00).',
      character: 'كريم',
      promptAr: 'اضبط ساعة المدرسة على 08:00.',
      activity: {
        id: 'act_apply_clock',
        promptAr: 'الساعة 08:00 تماماً',
        instructionAr: 'الساعة 8 و 00 دقيقة.',
        initialState: { hours: 5, minutes: 0 },
        targetState: { hours: 8, minutes: 0 },
        availableRepresentations: ['clock'],
        defaultRepresentation: 'clock',
        whyExplanation: {
          questionAr: 'لماذا 8 تماماً؟',
          answerAr: 'لأن العقرب الصغير عند 8 والكبير عند 12.',
          visualConcept: '08:00',
        },
        walkthroughSteps: [],
        hintAr: 'اضبط على 8 وتماماً.',
      },
    },
    transferTest: {
      promptAr: 'اضبط الساعة على الثالثة والنصف (03:30).',
      representation: 'clock',
      activity: {
        id: 'transfer_clock',
        promptAr: '03:30',
        instructionAr: 'الساعة 3 و 30 دقيقة.',
        initialState: { hours: 1, minutes: 0 },
        targetState: { hours: 3, minutes: 30 },
        availableRepresentations: ['clock'],
        defaultRepresentation: 'clock',
        whyExplanation: {
          questionAr: 'كيف نتأكد؟',
          answerAr: 'العقرب الصغير عند 3 والكبير عند 6.',
          visualConcept: '03:30',
        },
        walkthroughSteps: [],
        hintAr: 'اختر 3 والنصف.',
      },
    },
    whyExplanation: {
      questionAr: 'لماذا نربط الساعة بالروتين اليومي للطفل؟',
      answerAr: 'لأن قراءة الوقت مهارة حياتية يمارسها الطفل كل يوم في مواعيد نومه واستيقاظه ومدرسته!',
      interactiveDemoType: 'clock',
    },
  },

  // 14. قياس الأطوال بالمسطرة (السنتيمتر)
  {
    id: 'measurement_interactive',
    titleAr: 'مختبر قياس الأطوال بالمسطرة',
    subtitleAr: 'ابدأ القياس دائماً من نقطة الصفر (0)',
    category: 'time_and_measurement',
    worldId: 'measurement',
    icon: '📏',
    colorTheme: 'from-yellow-500 to-amber-700',
    conceptAr: 'قياس الأطوال بالمسطرة يبدأ من علامة الصفر (0) وليس من حافة الخشب الخارجية، ونقرأ الرقم عند الطرف الآخر.',
    objectiveAr: 'أن يقيس التلميذ طول جسم بالسنتيمتر واضعاً البداية عند 0 بدقة.',
    prerequisitesAr: ['قراءة الأعداد حتى 20'],
    supportedRepresentations: ['ruler'],
    storyIntro: {
      characterName: 'معمار القرية الكبير',
      scenarioAr: 'أحضر النجار قلم القصب البردي لقص خشب القارب، ونحتاج لمعرفة طوله الدقيق بالسنتيمتر!',
      dialogueAr: 'ضع طرف القلم عند الصفر (0) بالمسطرة، وانظر أين ينتهي الطرف الآخر!',
      sceneEmoji: '📏 [0 --------- 12 سم]',
    },
    prediction: {
      questionAr: 'من أين يجب أن تبدأ القياس بالمسطرة دائماً؟',
      options: [
        { id: 'opt1', textAr: 'من علامة الرقم صفر (0)', isCorrect: true, explanationAr: 'بطل! نقطة الصفر هي البداية الحقيقية لقياس الطول!' },
        { id: 'opt2', textAr: 'من حافة المسطرة الخشبية الخارجية', isCorrect: false, explanationAr: 'الحافة قد تحتوي فراغاً قبل الصفر يؤدي لخطأ في القياس!' },
        { id: 'opt3', textAr: 'من الرقم 1', isCorrect: false, explanationAr: 'إذا بدأت من 1 ستخسر سنتيمتراً كاملاً من القياس!' },
      ],
    },
    discoveryActivity: {
      id: 'act_discover_ruler',
      promptAr: 'قِس طول قلم القصب البردي الموضوع على المسطرة.',
      instructionAr: 'انظر للرقم الذي يقف عنده طرف القلم (12 سم) واكتبه.',
      initialState: { length: 12 },
      targetState: { length: 12 },
      availableRepresentations: ['ruler'],
      defaultRepresentation: 'ruler',
      whyExplanation: {
        questionAr: 'ليه بنبدأ من الصفر (0) ومش من (1)؟',
        answerAr: 'لأن الصفر يمثل "نقطة البداية" التي لم نقطع عندها أي مسافة بعد! المسافة بين 0 و 1 هي أول سنتيمتر كامل!',
        visualConcept: '0 ➡️ [ 1 سم ] ➡️ 1',
      },
      walkthroughSteps: [
        { titleAr: 'ثبّت البداية عند 0', textAr: 'طرف القلم الأيمن عند الصفر بالضبط.', visualHintAr: '0 cm' },
        { titleAr: 'اقرأ الطرف الآخر', textAr: 'ينتهي القلم عند الرقم 12 سم.', visualHintAr: '12 cm' },
        { titleAr: 'الطول النهائي', textAr: 'طول القلم 12 سنتيمتر (سم)!', visualHintAr: '12 سم' },
      ],
      hintAr: 'القلم يبدأ من 0 وينتهي عند 12، إذن طوله 12 سم.',
    },
    interactiveLab: {
      id: 'act_lab_ruler',
      promptAr: 'قِس طول مفتاح القلعة الذهبي.',
      instructionAr: 'ينتهي المفتاح عند الرقم 8 سم على المسطرة.',
      initialState: { length: 8 },
      targetState: { length: 8 },
      availableRepresentations: ['ruler'],
      defaultRepresentation: 'ruler',
      whyExplanation: {
        questionAr: 'ما هي وحدة قياس الأطوال الصغيرة؟',
        answerAr: 'السنتيمتر (سم) للأشياء الصغيرة مثل القلم والكتاب، والمتر (م) للأشياء الكبيرة مثل الغرفة والباب!',
        visualConcept: '1 متر 🟰 100 سنتيمتر',
      },
      walkthroughSteps: [],
      hintAr: 'طول المفتاح 8 سم.',
    },
    practiceChallenges: [],
    realWorldApplication: {
      scenarioAr: 'قاس زياد طول كراسة الرسم فوجدها 15 سم، وطول الممحاة 4 سم.',
      character: 'زياد',
      promptAr: 'أيهما أطول؟ كراسة الرسم أطول من الممحاة!',
      activity: {
        id: 'act_apply_ruler',
        promptAr: 'الكراسة 15 سم أطول من الممحاة 4 سم',
        instructionAr: 'قارن بين الطولين: 15 > 4.',
        initialState: { length: 15 },
        targetState: { length: 15 },
        availableRepresentations: ['ruler'],
        defaultRepresentation: 'ruler',
        whyExplanation: {
          questionAr: 'المقارنة بين الأطوال',
          answerAr: 'العدد الأكبر على المسطرة يعني طولاً أكبر!',
          visualConcept: '15 سم > 4 سم',
        },
        walkthroughSteps: [],
        hintAr: '15 سم أطول من 4 سم.',
      },
    },
    transferTest: {
      promptAr: 'إذا كان طول قلم تلوين 9 سم، فقِس طوله بالمسطرة.',
      representation: 'ruler',
      activity: {
        id: 'transfer_ruler',
        promptAr: 'الطول = 9 سم',
        instructionAr: 'اكتب 9.',
        initialState: { length: 9 },
        targetState: { length: 9 },
        availableRepresentations: ['ruler'],
        defaultRepresentation: 'ruler',
        whyExplanation: {
          questionAr: 'كيف عرفت؟',
          answerAr: 'لأنه يبدأ من 0 وينتهي عند 9 سم.',
          visualConcept: '9 سم',
        },
        walkthroughSteps: [],
        hintAr: '9 سم.',
      },
    },
    whyExplanation: {
      questionAr: 'ما هو الخطأ الأكثر شيوعاً في قياس الأطوال؟',
      answerAr: 'هو البدء من الرقم 1 أو من طرف المسطرة الخشبي! تذكر دائماً: البداية عند الرقم صفر (0)!',
      interactiveDemoType: 'ruler',
    },
  },

  // 15. الفصل الأول: الرسوم البيانية والجداول
  {
    id: 'data_graphs_tables',
    titleAr: 'الرسوم البيانية والجداول',
    subtitleAr: 'قراءة الرسوم البيانية بالأعمدة ومقارنة الفئات',
    category: 'number_patterns',
    worldId: 'forest',
    icon: '📊',
    colorTheme: 'from-emerald-500 to-teal-700',
    conceptAr: 'تمثيل البيانات في أعمدة رأسية لقراءة الأعداد الأكبر والأصغر بنظرة عين واحدة دون الحاجة للعد المتكرر.',
    objectiveAr: 'أن يقرأ التلميذ البيانات من الرسم البياني بالأعمدة ويقارن بين الفئات المختلفة.',
    prerequisitesAr: ['العد حتى 20', 'المقارنة (أكبر من / أصغر من)'],
    supportedRepresentations: ['objects', 'number_line'],
    storyIntro: {
      characterName: 'ميرو وحصاد الفواكه',
      scenarioAr: 'جمع ميرو وأصدقاؤه سلالاً من الفواكه: 5 تفاحات، 3 موزات، و 7 برتقالات!',
      dialogueAr: 'يا بطل! كيف نعرف الفاكهة الأكثر بسرعة فائقة؟ نبني بها أعمدة في الرسم البياني!',
      sceneEmoji: '🍎🍏🍌🍊 📊',
    },
    prediction: {
      questionAr: 'إذا بنينا عموداً لكل فاكهة، أي عمود سيكون الأطول؟',
      options: [
        { id: 'opt1', textAr: 'عمود البرتقال (7) لأنه العدد الأكبر', isCorrect: true, explanationAr: 'صحيح! العمود الأطول يمثل الفئة الأكثر عدداً!' },
        { id: 'opt2', textAr: 'عمود الموز (3)', isCorrect: false, explanationAr: 'الموز 3 فقط وهو أقصر عمود!' },
        { id: 'opt3', textAr: 'كل الأعمدة متساوية', isCorrect: false, explanationAr: 'الأعداد مختلفة: 7 و 5 و 3!' },
      ],
    },
    discoveryActivity: {
      id: 'act_discover_graphs',
      promptAr: 'شاهد أعمدة الفواكه: تفاح (5)، موز (3)، برتقال (7).',
      instructionAr: 'لاحظ كيف يدل ارتفاع العمود على عدد العناصر.',
      initialState: { apple: 5, banana: 3, orange: 7 },
      targetState: { highest: 'orange' },
      availableRepresentations: ['objects'],
      defaultRepresentation: 'objects',
      whyExplanation: {
        questionAr: 'ليه بنستخدم الرسم البياني بالأعمدة؟',
        answerAr: 'لأنه يحول الأرقام الكثيرة إلى صورة مرئية وسهلة المقارنة بنظرة واحدة!',
        visualConcept: '📊 ارتفاع العمود 🟰 كمية البيانات',
      },
      walkthroughSteps: [
        { titleAr: 'محاذاة البداية', textAr: 'كل الأعمدة تبدأ من خط الصفر في الأسفل.', visualHintAr: '0' },
        { titleAr: 'ارتفاع العمود', textAr: 'كل مربع يمثل عنصراً واحداً.', visualHintAr: '1 = 1' },
        { titleAr: 'قراءة القمة', textAr: 'قمة عمود البرتقال تصل إلى 7، إذن هو الأكثر!', visualHintAr: '7' },
      ],
      hintAr: 'البرتقال (7) هو صاحب أطول عمود في الرسم.',
    },
    interactiveLab: {
      id: 'act_lab_graphs',
      promptAr: 'كم يزيد عدد البرتقال (7) عن عدد الموز (3)؟',
      instructionAr: 'اطرح: 7 − 3 = 4.',
      initialState: { diff: 4 },
      targetState: { diff: 4 },
      availableRepresentations: ['objects'],
      defaultRepresentation: 'objects',
      whyExplanation: {
        questionAr: 'كيف نعرف الفرق بين عمودين؟',
        answerAr: 'نطرح ارتفاع العمود الصغير من ارتفاع العمود الكبير!',
        visualConcept: '7 ➖ 3 🟰 4',
      },
      walkthroughSteps: [],
      hintAr: '7 − 3 = 4.',
    },
    practiceChallenges: [],
    realWorldApplication: {
      scenarioAr: 'سأل المعلم تلاميذ الفصل عن هوايتهم المفضلة: 10 يفضلون الرسم، و 6 يفضلون السباحة.',
      character: 'سارة',
      promptAr: 'أي الهوايات حصلت على أعلى عمود؟ (الرسم)',
      activity: {
        id: 'act_apply_graphs',
        promptAr: 'الرسم (10) > السباحة (6)',
        instructionAr: 'حدد الهواية الأكثر شعبية.',
        initialState: { max: 'drawing' },
        targetState: { max: 'drawing' },
        availableRepresentations: ['objects'],
        defaultRepresentation: 'objects',
        whyExplanation: {
          questionAr: 'أين نستخدم الجداول في المدرسة؟',
          answerAr: 'في انتخابات الفصل، وجدول الحصص، وإحصاء الحضور والغياب!',
          visualConcept: '📋 تصويت الفصل',
        },
        walkthroughSteps: [],
        hintAr: 'الرسم حصل على 10 أصوات.',
      },
    },
    transferTest: {
      promptAr: 'إذا كان عدد الكرات الحمراء 8 والصفراء 8، ماذا تلاحظ في طول العمودين؟',
      representation: 'objects',
      activity: {
        id: 'transfer_graphs',
        promptAr: 'العمودان متساويان تماماً في الارتفاع (8 = 8)',
        instructionAr: 'الأعداد المتساوية تعطي أعمدة بنفس الارتفاع.',
        initialState: { equal: true },
        targetState: { equal: true },
        availableRepresentations: ['objects'],
        defaultRepresentation: 'objects',
        whyExplanation: {
          questionAr: 'ماذا يعني تساوي العمودين؟',
          answerAr: 'يعني أن الفئتين لهما نفس العدد بالضبط!',
          visualConcept: '8 🟰 8',
        },
        walkthroughSteps: [],
        hintAr: 'العمودان لهما نفس الارتفاع.',
      },
    },
    whyExplanation: {
      questionAr: 'ما هو سر قراءة الرسوم البيانية؟',
      answerAr: 'النظر لتدريج الأرقام على المحور الرأسي ومحاذاة قمة كل عمود لمعرفة رقمه بدقة!',
      interactiveDemoType: 'objects',
    },
  },

  // 16. الفصل السابع: وحدات السعة
  {
    id: 'capacity_liters',
    titleAr: 'وحدات السعة (اللتر والمليلتر)',
    subtitleAr: 'قياس كميات السوائل ومقارنة السعات',
    category: 'time_and_measurement',
    worldId: 'capacity',
    icon: '🧪',
    colorTheme: 'from-cyan-500 to-teal-600',
    conceptAr: 'السعة هي مقدار ما يتسع له الوعاء من سائل. نستخدم اللتر (ل) للسعات الكبيرة والمليلتر (مل) للسعات الصغيرة.',
    objectiveAr: 'أن يميز التلميذ بين اللتر والمليلتر ويدرك أن 1 لتر = 1000 مليلتر.',
    prerequisitesAr: ['مقارنة الكميات والأعداد حتى 1000'],
    supportedRepresentations: ['objects', 'vertical_equation'],
    storyIntro: {
      characterName: 'ميرو في مختبر الكيمياء السحري',
      scenarioAr: 'يحتاج ميرو إلى ملء قارورة إكسير سحرية سعتها 1 لتر كامل!',
      dialogueAr: 'يا بطل! هل نملأ القارورة الكبيرة بقطارة العين الصغيرة؟ أم بزجاجة اللتر الكبيرة؟',
      sceneEmoji: '🧪 💧 1L = 1000mL',
    },
    prediction: {
      questionAr: 'أي من الأوعية التالية يتسع لأكثر من لتر واحد من الماء؟',
      options: [
        { id: 'opt1', textAr: 'دلو غسيل الأرضيات أو حمام السباحة', isCorrect: true, explanationAr: 'صحيح! الدلو يسع عدة لترات!' },
        { id: 'opt2', textAr: 'ملعقة الشاي الصغيرة', isCorrect: false, explanationAr: 'الملعقة تسع 5 مل فقط!' },
        { id: 'opt3', textAr: 'قطارة الدواء', isCorrect: false, explanationAr: 'القطارة تسع 1 أو 2 مل فقط!' },
      ],
    },
    discoveryActivity: {
      id: 'act_discover_capacity',
      promptAr: 'قارن بين زجاجة الحليب (1 لتر) و ملعقة العسل (5 مليلتر).',
      instructionAr: 'اللتر للسوائل الكبيرة، والمليلتر للجرعات الصغيرة.',
      initialState: { liter: 1000, ml: 5 },
      targetState: { ratio: 200 },
      availableRepresentations: ['objects'],
      defaultRepresentation: 'objects',
      whyExplanation: {
        questionAr: 'كم مليلتر في اللتر الواحد؟',
        answerAr: '1 لتر = 1000 مليلتر بالضبط! اللتر يحتوي ألف نقطة مليلتر صغيرة!',
        visualConcept: '1 لتر 🟰 1000 مل',
      },
      walkthroughSteps: [
        { titleAr: 'وحدة اللتر (ل)', textAr: 'لقياس زجاجات العصير، المياه، وسوائل الوقود.', visualHintAr: '1L' },
        { titleAr: 'وحدة المليلتر (مل)', textAr: 'لقياس جرعات الأدوية والعطور والقطارات.', visualHintAr: '1mL' },
        { titleAr: 'العلاقة الذهبية', textAr: '1 لتر = 1000 مليلتر.', visualHintAr: '1000' },
      ],
      hintAr: 'اللتر = 1000 مليلتر.',
    },
    interactiveLab: {
      id: 'act_lab_capacity',
      promptAr: 'إذا شرب ميرو نصف لتر عصير (500 مل)، كم يتبقى من اللتر الكامل (1000 مل)؟',
      instructionAr: '1000 − 500 = 500 مل (نصف لتر).',
      initialState: { remaining: 500 },
      targetState: { remaining: 500 },
      availableRepresentations: ['vertical_equation'],
      defaultRepresentation: 'vertical_equation',
      whyExplanation: {
        questionAr: 'كم يساوي نصف اللتر؟',
        answerAr: 'نصف الألف (1000) هو 500 مليلتر!',
        visualConcept: 'نصف لتر 🟰 500 مل',
      },
      walkthroughSteps: [],
      hintAr: '1000 − 500 = 500 مل.',
    },
    practiceChallenges: [],
    realWorldApplication: {
      scenarioAr: 'اشترت أم ميرو زجاجة زيت سعتها 2 لتر، وزجاجة عصير سعتها 1 لتر.',
      character: 'أم ميرو',
      promptAr: 'كم لتراً من السوائل اشترت في المجموع؟ (2 + 1 = 3 لتر)',
      activity: {
        id: 'act_apply_capacity',
        promptAr: '2 لتر + 1 لتر = 3 لترات',
        instructionAr: 'اجمع كميات اللترات مباشرة.',
        initialState: { total: 3 },
        targetState: { total: 3 },
        availableRepresentations: ['objects'],
        defaultRepresentation: 'objects',
        whyExplanation: {
          questionAr: 'جمع السعات المتشابهة',
          answerAr: 'نجمع اللترات مع اللترات والمليلتر مع المليلتر!',
          visualConcept: '2L ➕ 1L 🟰 3L',
        },
        walkthroughSteps: [],
        hintAr: '2 + 1 = 3 لتر.',
      },
    },
    transferTest: {
      promptAr: 'قارورة مياه سعتها 750 مل، هل سعتها أكبر أم أصغر من لتر واحد (1000 مل)؟',
      representation: 'vertical_equation',
      activity: {
        id: 'transfer_capacity',
        promptAr: '750 مل < 1000 مل (أصغر من لتر)',
        instructionAr: '750 مل أقل من 1000 مل.',
        initialState: { result: 'smaller' },
        targetState: { result: 'smaller' },
        availableRepresentations: ['vertical_equation'],
        defaultRepresentation: 'vertical_equation',
        whyExplanation: {
          questionAr: 'المقارنة مع اللتر',
          answerAr: '750 مل تنقص 250 مل لتصل إلى لتر كامل!',
          visualConcept: '750 < 1000',
        },
        walkthroughSteps: [],
        hintAr: '750 مل أصغر من لتر.',
      },
    },
    whyExplanation: {
      questionAr: 'لماذا نحتاج وحدتين (لتر ومليلتر)؟',
      answerAr: 'لأنه من غير المنطقي قياس قطرة دواء باللتر أو قياس ماء الخزان بالمليلتر! كل حجم له وحدته المناسبة!',
      interactiveDemoType: 'objects',
    },
  },

  // 17. الفصل التاسع: طرق الحساب الذهني
  {
    id: 'mental_math_strategies',
    titleAr: 'طرق الحساب الذهني السريع',
    subtitleAr: 'استراتيجيات تكوين المائة والمضاعفة والتعويض الذكي',
    category: 'addition_strategies',
    worldId: 'castle',
    icon: '🧮',
    colorTheme: 'from-fuchsia-600 to-purple-900',
    conceptAr: 'استخدام تفكيك الأعداد والتعويض بمكملات العشرة والمائة لحساب النواتج بسرعة في العقل دون ورقة وقلم.',
    objectiveAr: 'أن يطبق التلميذ استراتيجيات الجمع الذهني السريع مثل تكوين الـ 100 وتجزئة الأعداد.',
    prerequisitesAr: ['حقائق الجمع حتى 100'],
    supportedRepresentations: ['ten_frame', 'number_line', 'vertical_equation'],
    storyIntro: {
      characterName: 'طيف ملك الأرقام في قلعة الحساب',
      scenarioAr: 'يقف ميرو أمام عرش الحساب الذهني ويطلب منه الملك حل 49 + 35 في ثانية واحدة!',
      dialogueAr: 'يا بطل! أسرع طريقة: اجعل 49 تصبح 50 (أضف 1)، فتصبح 50 + 34 = 84! ذكاء وسرعة مذهلة!',
      sceneEmoji: '⚡ 49 + 35 ➡️ 50 + 34 = 84',
    },
    prediction: {
      questionAr: 'ما هو مكمل العدد 80 ليصبح 100 في الحساب الذهني السريع؟',
      options: [
        { id: 'opt1', textAr: '20 (لأن 8 عشرات + 2 عشرات = 10 عشرات)', isCorrect: true, explanationAr: 'عبقري! 80 + 20 = 100!' },
        { id: 'opt2', textAr: '30', isCorrect: false, explanationAr: '80 + 30 = 110!' },
        { id: 'opt3', textAr: '10', isCorrect: false, explanationAr: '80 + 10 = 90!' },
      ],
    },
    discoveryActivity: {
      id: 'act_discover_mental',
      promptAr: 'استخدم استراتيجية التعويض لحل: 39 + 25.',
      instructionAr: '39 قريبة جداً من 40! خذ 1 من 25 وضعه على 39: فتصبح 40 + 24 = 64!',
      initialState: { step1: 40, step2: 24 },
      targetState: { total: 64 },
      availableRepresentations: ['number_line'],
      defaultRepresentation: 'number_line',
      whyExplanation: {
        questionAr: 'ليه استراتيجية التعويض ذكية؟',
        answerAr: 'لأن الجمع مع الأعداد الصفرية (10، 20، 30، 40، 50، 100) سهل وسريع جداً على عقل الإنسان!',
        visualConcept: '39 ➕ 25 🟰 40 ➕ 24 🟰 64',
      },
      walkthroughSteps: [
        { titleAr: 'قرّب للرقم السهل', textAr: '39 ينقصها 1 لتصبح 40.', visualHintAr: '39 + 1 = 40' },
        { titleAr: 'انقص من الطرف الثاني', textAr: '25 تنقص 1 فتصبح 24.', visualHintAr: '25 - 1 = 24' },
        { titleAr: 'اجمع في ثانية', textAr: '40 + 24 = 64 فوراً!', visualHintAr: '64' },
      ],
      hintAr: '40 + 24 = 64.',
    },
    interactiveLab: {
      id: 'act_lab_mental',
      promptAr: 'حل ذهنياً: 70 + ؟ = 100.',
      instructionAr: 'مكمل 70 إلى 100 هو 30.',
      initialState: { complement: 30 },
      targetState: { complement: 30 },
      availableRepresentations: ['number_line'],
      defaultRepresentation: 'number_line',
      whyExplanation: {
        questionAr: 'كيف نجد مكمل المائة في ثانية؟',
        answerAr: 'اسأل نفسك: 7 عشرات ينقصها كام وتصبح 10 عشرات؟ ينقصها 3 عشرات (30)!',
        visualConcept: '70 ➕ 30 🟰 100',
      },
      walkthroughSteps: [],
      hintAr: '70 + 30 = 100.',
    },
    practiceChallenges: [],
    realWorldApplication: {
      scenarioAr: 'مع كريم 95 جنيهاً، ويريد شراء لعبة بـ 100 جنيه.',
      character: 'كريم',
      promptAr: 'كم جنيهاً ينقصه ذهنياً؟ (5 جنيهات فقط!)',
      activity: {
        id: 'act_apply_mental',
        promptAr: '100 − 95 = 5 جنيهات',
        instructionAr: 'احسب الفرق ذهنياً.',
        initialState: { diff: 5 },
        targetState: { diff: 5 },
        availableRepresentations: ['number_line'],
        defaultRepresentation: 'number_line',
        whyExplanation: {
          questionAr: 'الحساب الذهني في الشراء',
          answerAr: 'يساعدك على معرفة الباقي فوراً وحساب نقودك بدقة دون تردد!',
          visualConcept: '95 ➕ 5 🟰 100',
        },
        walkthroughSteps: [],
        hintAr: 'ينقصه 5 جنيهات.',
      },
    },
    transferTest: {
      promptAr: 'احسب ذهنياً: ضعف العدد 25 ثم أضف 50 = ؟',
      representation: 'number_line',
      activity: {
        id: 'transfer_mental',
        promptAr: 'ضعف 25 هو 50، ثم 50 + 50 = 100!',
        instructionAr: '25 + 25 = 50، 50 + 50 = 100.',
        initialState: { ans: 100 },
        targetState: { ans: 100 },
        availableRepresentations: ['number_line'],
        defaultRepresentation: 'number_line',
        whyExplanation: {
          questionAr: 'قوة المضاعفات في الحساب الذهني',
          answerAr: 'المضاعفات المتتالية تصنع المائة بسرعة وسهولة!',
          visualConcept: '25 ➡️ 50 ➡️ 100',
        },
        walkthroughSteps: [],
        hintAr: 'الناتج 100.',
      },
    },
    whyExplanation: {
      questionAr: 'لماذا يعتبر الحساب الذهني مهارة الأبطال؟',
      answerAr: 'لأنه يطور التفكير المنطقي والمرونة الذهنية ويجعل الرياضيات ممتعة ومفيدة في الحياة اليومية!',
      interactiveDemoType: 'number_line',
    },
  },
];
