import { WorldRegion, Skill, HomeItem, Pet, Misconception } from '../types/game';

export const MISCONCEPTIONS_CATALOG: Record<string, Misconception> = {
  counting_error: {
    tag: 'counting_error',
    labelAr: 'خطأ في العد اليدوي',
    remedyAr: 'تدريب الطفل على تأشير كل عنصر بإصبعه أثناء العد خطوة بخطوة.',
    sampleTrigger: 'العد غير الدقيق للعناصر',
  },
  most_least_inverted: {
    tag: 'most_least_inverted',
    labelAr: 'الخلط بين (الأكثر) و (الأقل)',
    remedyAr: 'التأكيد البصري: "الأكثر" يعني العمود الأطول ذو القمة المرتفعة، و"الأقل" هو الأقصر.',
    sampleTrigger: 'اختيار أصغر عمود عند السؤال عن الأكثر',
  },
  difference_vs_sum: {
    tag: 'difference_vs_sum',
    labelAr: 'الخلط بين "كم يزيد؟" وبين الجمع',
    remedyAr: 'توضيح أن "كم يزيد" تعني مقارنة وطرح الفرق بين العمودين وليس ضمهما.',
    sampleTrigger: 'جمع القيمتين بدلاً من طرحهما',
  },
  place_value_confusion: {
    tag: 'place_value_confusion',
    labelAr: 'الخلط بين العشرات والآحاد',
    remedyAr: 'استخدام أعمدة العشرات ومربعات الآحاد المنفصلة.',
    sampleTrigger: 'قراءة 53 كـ 35',
  },
  time_hand_confusion: {
    tag: 'time_hand_confusion',
    labelAr: 'الخلط بين عقرب الساعات وعقرب الدقائق',
    remedyAr: 'العقرب الصغير للساعة الكسولة، والعقرب الطويل للدقائق السريعة.',
    sampleTrigger: 'قراءة الدقائق كساعات',
  },
};

export const WORLDS: WorldRegion[] = [
  {
    id: 'forest',
    chapterNumber: 1,
    nameAr: 'الفصل الأول: الرسوم البيانية والجداول',
    titleAr: 'الرسوم البيانية والجداول',
    chapterSubtitleAr: 'نتعلّم قراءة الرسوم البيانية والجداول ومقارنتها وتحليلها.',
    descriptionAr: 'اجمع فواكه النيل وشيّد المدرج البياني بالأعمدة ومقارنة الفئات وتحليل الجداول.',
    themeColor: 'from-emerald-500 to-teal-700',
    requiredStars: 0,
    crystalNameAr: 'بلورة البيانات الخضراء',
    isUnlocked: true,
    isCompleted: false,
    bossNameAr: 'حارس الغابة الحكيم "عم هدهد"',
    icon: '📊',
    x: 22,
    y: 72,
  },
  {
    id: 'addition',
    chapterNumber: 2,
    nameAr: 'الفصل الثاني: الجمع الرأسي',
    titleAr: 'الجمع الرأسي',
    chapterSubtitleAr: 'نتعلّم جمع الأعداد بالطريقة الرأسية بمهارة ودقة.',
    descriptionAr: 'اجمع أحجار الأرقام لترميم جسور الوادي بجمع الأعداد حتى 100 بالخوارزمية الرأسية وإعادة التسمية.',
    themeColor: 'from-amber-500 to-orange-600',
    requiredStars: 0,
    crystalNameAr: 'بلورة الجمع الذهبية',
    isUnlocked: true,
    isCompleted: false,
    bossNameAr: 'عملاق الوادي الصخري',
    icon: '➕',
    x: 42,
    y: 65,
  },
  {
    id: 'subtraction',
    chapterNumber: 3,
    nameAr: 'الفصل الثالث: الطرح الرأسي',
    titleAr: 'الطرح الرأسي',
    chapterSubtitleAr: 'نتعلّم طرح الأعداد بالطريقة الرأسية ونتحقق من الإجابة.',
    descriptionAr: 'استخدم الطرح الرأسي بتفكيك العشرات وإعادة التسمية لفتح بوابات الكهف والتحقق من النواتج.',
    themeColor: 'from-violet-500 to-indigo-700',
    requiredStars: 0,
    crystalNameAr: 'بلورة الطرح البنفسجية',
    isUnlocked: true,
    isCompleted: false,
    bossNameAr: 'خفاش الكهف المضيء',
    icon: '➖',
    x: 65,
    y: 70,
  },
  {
    id: 'time',
    chapterNumber: 4,
    nameAr: 'الفصل الرابع: الوقت والمدة الزمنية',
    titleAr: 'الوقت والمدة الزمنية',
    chapterSubtitleAr: 'نتعلّم قراءة الوقت وحساب المدة الزمنية في حياتنا اليومية.',
    descriptionAr: 'اضبط عقارب الساعات واقرأ الوقت تماماً وبالنصف والربع واحسب الفترات الزمنية.',
    themeColor: 'from-sky-500 to-blue-700',
    requiredStars: 0,
    crystalNameAr: 'بلورة الزمن السماوية',
    isUnlocked: true,
    isCompleted: false,
    bossNameAr: 'طائر الساعة الذهبي',
    icon: '⏰',
    x: 78,
    y: 50,
  },
  {
    id: 'measurement',
    chapterNumber: 5,
    nameAr: 'الفصل الخامس: وحدات الطول',
    titleAr: 'وحدات الطول',
    chapterSubtitleAr: 'نتعلّم قياس الأطوال باستخدام وحدات مختلفة.',
    descriptionAr: 'استخدم مسطرة السنتيمتر والمتر لقياس الأطوال من الصفر وتشييد مباني وقوارب النيل.',
    themeColor: 'from-yellow-500 to-amber-700',
    requiredStars: 0,
    crystalNameAr: 'بلورة القياس النحاسية',
    isUnlocked: true,
    isCompleted: false,
    bossNameAr: 'معمار القرية الكبير',
    icon: '📏',
    x: 55,
    y: 42,
  },
  {
    id: 'numbers',
    chapterNumber: 6,
    nameAr: 'الفصل السادس: أعداد أكبر من ١٠٠',
    titleAr: 'أعداد أكبر من ١٠٠',
    chapterSubtitleAr: 'نتعلّم قراءة الأعداد الكبيرة ومقارنتها وترتيبها.',
    descriptionAr: 'اكتشف القيمة المكانية للمئات والعشرات والآحاد وقارن ورتّب الأعداد المكونة من ثلاثة أرقام.',
    themeColor: 'from-orange-400 to-rose-600',
    requiredStars: 0,
    crystalNameAr: 'بلورة القيمة المكانية الحمراء',
    isUnlocked: true,
    isCompleted: false,
    bossNameAr: 'حارس الأهرامات الرملي',
    icon: '🧱',
    x: 32,
    y: 38,
  },
  {
    id: 'capacity',
    chapterNumber: 7,
    nameAr: 'الفصل السابع: وحدات السعة',
    titleAr: 'وحدات السعة',
    chapterSubtitleAr: 'نتعلّم قياس السعة باستخدام وحدات السعة المختلفة.',
    descriptionAr: 'قِس كميات المياه وإكسير السحر باستخدام اللتر والمليلتر لتشغيل نوافير المملكة.',
    themeColor: 'from-cyan-500 to-teal-600',
    requiredStars: 0,
    crystalNameAr: 'بلورة السعة الفيروزية',
    isUnlocked: true,
    isCompleted: false,
    bossNameAr: 'كيميائي المختبر الحكيم',
    icon: '🧪',
    x: 20,
    y: 25,
  },
  {
    id: 'mixed',
    chapterNumber: 8,
    nameAr: 'الفصل الثامن: الجمع والطرح الرأسي',
    titleAr: 'الجمع والطرح الرأسي',
    chapterSubtitleAr: 'نتعلّم جمع الأعداد وطرحها بالطريقة الرأسية ونتقنها.',
    descriptionAr: 'اتقان دمج الجمع والطرح الرأسي مع إعادة التسمية وحل المسائل الكلامية والتحقق بالعلاقة العكسية.',
    themeColor: 'from-pink-500 to-rose-700',
    requiredStars: 0,
    crystalNameAr: 'بلورة الحكمة الوردية',
    isUnlocked: true,
    isCompleted: false,
    bossNameAr: 'كبير تجار السوق',
    icon: '📝',
    x: 48,
    y: 20,
  },
  {
    id: 'castle',
    chapterNumber: 9,
    nameAr: 'الفصل التاسع: طرق الحساب الذهني',
    titleAr: 'طرق الحساب الذهني',
    chapterSubtitleAr: 'نتعلّم طرق الحساب الذهنية السريعة والسهلة بذكاء.',
    descriptionAr: 'التحدي النهائي! استعمل استراتيجيات مكملات العشرة والمائة والمضاعفة والعد السريع لإنقاذ المملكة!',
    themeColor: 'from-fuchsia-600 to-purple-900',
    requiredStars: 0,
    crystalNameAr: 'بلورة المملكة التاجية',
    isUnlocked: true,
    isCompleted: false,
    bossNameAr: 'طيف ملك الأرقام القديم',
    icon: '🧮',
    x: 75,
    y: 18,
  },
];

export const GRADE_2_SKILLS: Skill[] = [
  {
    id: 'skill_data_collect',
    worldId: 'forest',
    titleAr: 'جمع البيانات وتصنيفها',
    grade2Competency: 'تصنيف وجمع البيانات من البيئة المحيطة وتسجيلها',
    conceptAr: 'حصر العناصر المتشابهة وحساب أعدادها',
    difficulty: 1,
    hints: [
      'عدّ كل نوع من الفاكهة بلطف.',
      'ضع أصبعك على كل حبة تفاح وعد: 1، 2، 3...',
      'اجمع كل فاكهة في سلتها المخصصة.',
    ],
    commonMistakes: [MISCONCEPTIONS_CATALOG.counting_error],
  },
  {
    id: 'skill_graph_build',
    worldId: 'forest',
    titleAr: 'إنشاء وقراءة المدرج البياني بالأعمدة',
    grade2Competency: 'تمثيل البيانات بالأعمدة الرأسية وقراءتها بدقة',
    conceptAr: 'طول العمود يعبر عن العدد',
    difficulty: 1,
    hints: [
      'كل مكعب في العمود يمثل فاكهة واحدة.',
      'اسحب المربعات للأعلى حتى تصل للرقم المطلوب على المسطرة الجانبية.',
      'العمود الأطول يعني كمية أكبر.',
    ],
    commonMistakes: [MISCONCEPTIONS_CATALOG.counting_error],
  },
  {
    id: 'skill_graph_compare',
    worldId: 'forest',
    titleAr: 'مقارنة البيانات (الأكثر والأقل والفرق)',
    grade2Competency: 'المقارنة بين فئات التمثيل البياني واستنتاج الفروق',
    conceptAr: 'تحديد الأكثر والأقل وحساب الزيادة',
    difficulty: 2,
    hints: [
      'انظر إلى قمم الأعمدة.. أيها يعلو الجميع؟',
      'الأكثر هو العمود الأطول، والأقل هو العمود الأقصر.',
      'لحساب "كم يزيد؟"، نطرح العدد الصغير من العدد الكبير.',
    ],
    commonMistakes: [
      MISCONCEPTIONS_CATALOG.most_least_inverted,
      MISCONCEPTIONS_CATALOG.difference_vs_sum,
    ],
  },
  {
    id: 'skill_addition_2digit',
    worldId: 'addition',
    titleAr: 'جمع عددين من رقمين مع إعادة التسمية',
    grade2Competency: 'جمع عددين حتى 100 مع إعادة التسمية إلى العشرات',
    conceptAr: 'عندما يتعدى الآحاد 9، نرحل عشرة كاملة لعمود العشرات',
    difficulty: 2,
    hints: [
      'اجمع خانة الآحاد أولاً.',
      'إذا كان الناتج 10 أو أكثر، ضع عشرة في عمود العشرات.',
      'ثم اجمع العشرات مع العشرة الجديدة.',
    ],
    commonMistakes: [MISCONCEPTIONS_CATALOG.place_value_confusion],
  },
  {
    id: 'skill_time_reading',
    worldId: 'time',
    titleAr: 'قراءة الوقت بالساعة والنصف ساعة',
    grade2Competency: 'قراءة الساعات ذات العقارب بالساعة التامة والنصف والربع',
    conceptAr: 'العقرب القصير للساعات والعقرب الطويل للدقائق',
    difficulty: 2,
    hints: [
      'العقرب الصغير يشير إلى رقم الساعة.',
      'عندما يكون العقرب الطويل عند 6، فالوقت ونصف (30 دقيقة).',
      'عندما يكون العقرب الطويل عند 12، فالساعة تماماً.',
    ],
    commonMistakes: [MISCONCEPTIONS_CATALOG.time_hand_confusion],
  },
  {
    id: 'skill_measurement_cm',
    worldId: 'measurement',
    titleAr: 'القياس بالسنتيمتر',
    grade2Competency: 'تقدير وقياس أطوال الأشياء بالسنتيمتر باستخدام المسطرة',
    conceptAr: 'نبدأ القياس دائماً من الصفر (0)',
    difficulty: 1,
    hints: [
      'تأكد أن بداية الشيء عند الرقم صفر في المسطرة.',
      'انظر أين ينتهي طرف الشيء.. هذا هو الطول بالسنتيمتر.',
    ],
    commonMistakes: [],
  },
];

export const PETS_CATALOG: Pet[] = [
  {
    id: 'fennec',
    nameAr: 'ثعلوب',
    animalAr: 'ثعلب الفنك المصري',
    descriptionAr: 'صديق ذكي سريع البديهة يعشق حل الألغاز والمغامرة في الصحراء والنيل.',
    cost: 0,
    icon: '🦊',
    animation: 'bounce',
    unlockedByDefault: true,
  },
  {
    id: 'cat',
    nameAr: 'مشمش',
    animalAr: 'قط النيل الذهبي',
    descriptionAr: 'قط أليف مرح يحب القفز على الأرقام واصطياد العملات اللامعة.',
    cost: 50,
    icon: '🐱',
    animation: 'wiggle',
  },
  {
    id: 'hippo',
    nameAr: 'زيزو',
    animalAr: 'فرس النهر الصغير',
    descriptionAr: 'فرس نهر ودود وقوي يحب السباحة في ترع النيل ومساعدة الأصدقاء.',
    cost: 100,
    icon: '🦛',
    animation: 'splash',
  },
  {
    id: 'falcon',
    nameAr: 'صقر',
    animalAr: 'صقر الوادي السريع',
    descriptionAr: 'يطير فوق المملكة لاكتشاف البلورات المفقودة من أعالي السماء.',
    cost: 150,
    icon: '🦅',
    animation: 'fly',
  },
];

export const HOME_ITEMS_CATALOG: HomeItem[] = [
  {
    id: 'cozy_bed',
    nameAr: 'سرير المغامر الوثير',
    category: 'furniture',
    cost: 0,
    icon: '🛏️',
    unlockedByDefault: true,
  },
  {
    id: 'plant_pot',
    nameAr: 'نبتة بردي نيلية',
    category: 'plant',
    cost: 0,
    icon: '🪴',
    unlockedByDefault: true,
  },
  {
    id: 'desk',
    nameAr: 'مكتب العالم الصغير',
    category: 'furniture',
    cost: 40,
    icon: '🪑',
  },
  {
    id: 'crystal_stand',
    nameAr: 'حامل البلورات السحرية',
    category: 'trophy',
    cost: 60,
    icon: '🔮',
  },
  {
    id: 'papyrus_map',
    nameAr: 'خريطة البردي الأثرية',
    category: 'decoration',
    cost: 50,
    icon: '📜',
  },
  {
    id: 'telescope',
    nameAr: 'مرقب النجوم الذهبي',
    category: 'decoration',
    cost: 80,
    icon: '🔭',
  },
  {
    id: 'pharaoh_chest',
    nameAr: 'صندوق الكنوز المرصع',
    category: 'trophy',
    cost: 100,
    icon: '💎',
  },
];
